#  Kosmos. Copyright (c) 2026 Diego Cibils. MIT; see LICENSE.
#  The Kosmos Board on Cloudflare: one Worker for the API and the page, one
#  D1 database, made 9 October 2026. The Cloudflare account is not named here:
#  wrangler takes it from CLOUDFLARE_ACCOUNT_ID (`tools/board/README.md`).

name = "kosmos-board"
main = "src/worker.js"
compatibility_date = "2026-04-01"

[assets]
directory = "public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "kosmos-board"
database_id = "40f8af4b-41e9-46b6-9728-2afc8e96991e"
