/* Kosmos. Copyright (c) 2026 Diego Cibils. MIT; see LICENSE. */
/*
 * init: the first Lua process.
 *
 * It sets up the heap the kernel mapped for it, opens a lua_State, and runs
 * a chunk built into the image. There is no filesystem to load one from
 * until M8, and no namespace to ask until M5.
 */

#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include "lua.h"
#include "lauxlib.h"
#include "kosmos.h"
#include <tls.h>
#include <errno.h>
#include "kosmos_lua.h"

/* Generated by tools/bin2c.py from user/init/init.lua. NUL terminated past
 * init_lua_len, so it can be used as a string. */
extern const unsigned char init_lua[];
extern const unsigned long init_lua_len;

#ifdef KOSMOS_TEST
/*
 * The second chunk, in the test image only.
 *
 * `user/tests/luatest.lua` holds the Lua tests that used to run inside the
 * kernel. It is a separate chunk rather than more roles in init.lua because
 * it must not reach the image that ships, and Lua source cannot be compiled
 * out of a chunk the way C can.
 *
 * A boot word at or above LUATEST_BASE selects it. The bases do not overlap,
 * so a role number can only mean one of the two.
 */
extern const unsigned char luatest_lua[];
extern const unsigned long luatest_lua_len;

#define LUATEST_BASE    1000UL
#endif

#ifdef KOSMOS_BENCH
/* The same arrangement for the benchmark image. `user/tests/luabench.lua`
 * measures what Lua costs, out here where Lua runs. */
extern const unsigned char luabench_lua[];
extern const unsigned long luabench_lua_len;

#define LUABENCH_BASE   2000UL
#endif

/*
 * The audio server, which is C and does not want a `lua_State` at all.
 *
 * Dispatched before the interpreter is opened rather than after, and that
 * is the point rather than an optimisation: `CLAUDE.md` says a server runs
 * on behalf of another process and therefore does not get a collector, and
 * the way to mean that is for there to be no collector in the process. A
 * server that merely promises not to allocate is a server somebody adds a
 * `print` to next month.
 */
void audio_server(long endpoint);
void devices_server(long endpoint);
void binfs_server(long endpoint, int libraries);
void appfs_server(long endpoint);
void console_server(long endpoint);
void ramfs_server(long endpoint);
void net_server(long endpoint, long frames, long frames2);

/* Not a server anyone asks, and handed the console's endpoint rather than an
 * endpoint of its own: it is a driver, and it reports as a client. */
void powerbutton_server(long console);
void backlight_server(long console, long endpoint);
void xhci_server(long console, long blocks, long writes, long frames,
                 long camera);
void e1000_server(long console, long frames);

/* Its own endpoint, the USB driver's *read* endpoint, and the console's.
 * Never the write endpoint: `/drives` is read-only by what it was handed
 * rather than by what it agrees to. */
void drives_server(long endpoint, long blocks, long console);

#define ROLE_AUDIO    16UL
#define ROLE_DEVICES   9UL
#define ROLE_BINFS    11UL
#define ROLE_LIBFS    13UL
#define ROLE_APPFS    14UL
#define ROLE_CONSOLE   4UL
#define ROLE_RAMFS     1UL
#define ROLE_NET      17UL
#define ROLE_POWERBUTTON 18UL
#define ROLE_XHCI     19UL
#define ROLE_E1000    22UL
#define ROLE_DRIVES   20UL
#define ROLE_BACKLIGHT 21UL

static void say(const char *s)
{
    (void)kosmos_write(s, strlen(s));
}

#ifdef KOSMOS_TEST
/*
 * **Threads, in C, because Lua cannot hand the kernel an entry point**
 * (`threads.md` step 3).
 *
 * A boot word of `CTEST_THREADS` runs this instead of opening an
 * interpreter: it starts a second thread, waits for it, and exits with a
 * code the kernel's suite reads. The thread counts to a number in memory
 * both share - which is the point of a thread rather than a process - and
 * gives back a code of its own.
 *
 * Deliberately out here rather than inside the kernel's tests: this is a
 * *user* thread, with its own stack the kernel made and its own `errno`, and
 * a test that made one in the kernel would prove something else.
 */
#define CTEST_THREADS   900UL

static volatile unsigned long counted;

static void counts_to_a_thousand(unsigned long arg)
{
    /* Sixteen bytes on this thread's own stack, stored and loaded as one
     * vector - an aligned SSE move on x86, which faults if the thread began
     * with its stack where a function does not expect it. The kernel
     * started threads a word off until 25 September, and the 3D Kit's
     * workers were the first to notice (`user_function_sp`). */
    volatile float v __attribute__((vector_size(16))) = { 1, 2, 3, 4 };
    unsigned long i;

    v = v + v;

    for (i = 0; i < arg; i++) {
        counted++;
    }

    if (v[3] != 8) {
        kosmos_thread_exit(8);
    }

    /* Its own `errno`, which is the other half of step 2: set here, and read
     * by the first thread after this one has gone. */
    errno = 42;
    kosmos_thread_exit(7);
}

static int threads_role(void)
{
    long index;
    long code;

    errno = 11;
    index = kosmos_thread_start(counts_to_a_thousand, 1000UL);

    if (index < 0) {
        return 1;
    }

    code = kosmos_thread_wait((unsigned long)index);

    if (code != 7) {
        return 2;
    }

    if (counted != 1000UL) {
        return 3;
    }

    /* The other thread set its own to 42; this one still reads what it set,
     * because they are different blocks. */
    if (errno != 11) {
        return 4;
    }

    /* Waiting again for a thread that has been waited for says there is no
     * such thread: its slot went back when its code was read. */
    if (kosmos_thread_wait((unsigned long)index) >= 0) {
        return 5;
    }

    return 0;
}

/*
 * **A process whose threads end it from anywhere** (`threads.md` step 6).
 * Three roles, each a process the kernel's suite starts and times, and
 * each ends while a thread of it is somewhere a thread cannot be told to
 * leave by being at user level: asleep for a minute, waiting for a sibling
 * that never ends, spinning. Until 25 September the first of them panicked
 * the kernel after five seconds.
 */
#define CTEST_WORKER_FAULTS     901UL   /* a worker faults; the first sleeps */
#define CTEST_FAULT_WHILE_JOINED 902UL  /* one spins, one faults, the first waits */
#define CTEST_FIRST_LEAVES      903UL   /* the first returns; one sleeps, one spins */

#define A_MINUTE                (60UL * 250UL)  /* scheduler ticks, at 250 Hz */

/* Stores to `nowhere`, which is an address with nothing mapped: given
 * rather than written here, which the compiler would refuse to compile. */
static void faults(unsigned long nowhere)
{
    *(volatile unsigned long *)nowhere = 1;
    kosmos_thread_exit(9);                  /* not reached */
}

#define NOWHERE                 8UL

static void spins(unsigned long arg)
{
    (void)arg;

    for (;;) {
        counted++;
    }
}

static void sleeps(unsigned long ticks)
{
    kosmos_sleep(ticks);
    kosmos_thread_exit(0);
}

static int worker_faults_role(void)
{
    if (kosmos_thread_start(faults, NOWHERE) < 0) {
        return 1;
    }

    kosmos_sleep(A_MINUTE);
    return 2;                               /* the fault ended it before this */
}

static int fault_while_joined_role(void)
{
    long spinner = kosmos_thread_start(spins, 0);

    if (spinner < 0 || kosmos_thread_start(faults, NOWHERE) < 0) {
        return 1;
    }

    (void)kosmos_thread_wait((unsigned long)spinner);
    return 2;
}

static int first_leaves_role(void)
{
    if (kosmos_thread_start(sleeps, A_MINUTE) < 0
        || kosmos_thread_start(spins, 0) < 0) {
        return 1;
    }

    return 5;                               /* the process's code, at once */
}
#endif

/* What this process calls itself, which is what `procs` and `kill` show. */
static void named(const char *s)
{
    (void)kosmos_setname(s, strlen(s));
}

int main(unsigned long arg)
{
    lua_State *L;
    int status;
    const unsigned char *chunk;
    unsigned long chunk_len;
    const char *chunkname;
    unsigned long base = 0;

    /* The kernel gave this thread its block before it ran a single
     * instruction (`USER_TBLOCK`), so `errno` works from here without
     * anything being set up. */

#ifdef KOSMOS_TEST
    if (arg == CTEST_THREADS) {
        return threads_role();
    }

    if (arg == CTEST_WORKER_FAULTS) {
        return worker_faults_role();
    }

    if (arg == CTEST_FAULT_WHILE_JOINED) {
        return fault_while_joined_role();
    }

    if (arg == CTEST_FIRST_LEAVES) {
        return first_leaves_role();
    }
#endif

    /*
     * The heap is memory the kernel mapped at a fixed address, not memory
     * asked for. A process cannot grow its own heap yet and does not need
     * to: `design.md` §5.2 wants a bounded one anyway, because a small heap
     * collects fast and the maximum GC pause is what decides whether the
     * system stutters.
     */
    heap_init((void *)USER_HEAP, USER_HEAP_SIZE);

    /*
     * Before Lua, and it never comes back.
     *
     * The capability table a spawned process is handed puts its own
     * endpoint first, which is the same arrangement every Lua server here
     * relies on - this one just does not need a chunk loaded to find it.
     */
    /*
     * Each of these says what it is before it starts serving.
     *
     * `sys.name` was a line in every Lua role and went out with them, which
     * nobody noticed until a screenshot of `procs` showed five processes
     * called `init`: a process's name is whatever it last said it was, and a
     * server that says nothing keeps the name of the image it was spawned
     * from. It costs one syscall at startup and it is the only way anything
     * can tell these apart.
     */
    if (arg == ROLE_AUDIO) {
        named("audio");
        audio_server(0);
    }

    if (arg == ROLE_DEVICES) {
        named("devices");
        devices_server(0);
    }

    if (arg == ROLE_BINFS) {
        named("binfs");
        binfs_server(0, 0);
    }

    if (arg == ROLE_LIBFS) {
        named("libfs");
        binfs_server(0, 1);
    }

    if (arg == ROLE_APPFS) {
        named("appfs");
        appfs_server(0);
    }

    if (arg == ROLE_CONSOLE) {
        named("console");
        console_server(0);
    }

    if (arg == ROLE_RAMFS) {
        named("ramfs");
        ramfs_server(0);
    }

    if (arg == ROLE_NET) {
        named("net");
        net_server(0, 1, 2);
    }

    if (arg == ROLE_POWERBUTTON) {
        named("powerbutton");
        powerbutton_server(0);
    }

    if (arg == ROLE_BACKLIGHT) {
        named("backlight");
        backlight_server(0, 1);
    }

    if (arg == ROLE_XHCI) {
        named("xhci");
        xhci_server(0, 1, 2, 3, 4);
    }

    if (arg == ROLE_E1000) {
        named("e1000");
        e1000_server(0, 1);
    }

    if (arg == ROLE_DRIVES) {
        named("drives");
        drives_server(0, 1, 2);
    }

    L = kosmos_lua_open();
    if (L == NULL) {
        say("init: no memory for a lua_State\n");
        return 1;
    }

    /*
     * Which chunk, and which role within it.
     *
     * `base` is subtracted from the boot word rather than the chunk being
     * told what it is, so a role number inside a chunk means the same thing
     * whether it arrived from the kernel or from a sibling's spawn.
     */
    chunk = init_lua;
    chunk_len = init_lua_len;
    chunkname = "=init";     /* the leading = is Lua's "this is not a file" */

#ifdef KOSMOS_TEST
    if (arg >= LUATEST_BASE) {
        chunk = luatest_lua;
        chunk_len = luatest_lua_len;
        chunkname = "=luatest";
        base = LUATEST_BASE;
    }
#endif

#ifdef KOSMOS_BENCH
    if (arg >= LUABENCH_BASE) {
        chunk = luabench_lua;
        chunk_len = luabench_lua_len;
        chunkname = "=luabench";
        base = LUABENCH_BASE;
    }
#endif

    /*
     * The boot word reaches the chunk as its `...`, the same way a spawned
     * thread's capability did in the kernel's copy. A process is told one
     * thing and handed a capability table; everything else it works out.
     *
     * The base goes with it, because a chunk that spawns a sibling has to
     * put it back on to name a role in itself.
     */
    status = luaL_loadbufferx(L, (const char *)chunk, chunk_len, chunkname, "t");

    if (status == LUA_OK) {
        lua_pushinteger(L, (lua_Integer)(arg - base));
        lua_pushinteger(L, (lua_Integer)base);
        status = lua_pcall(L, 2, 0, 0);
    }

    if (status != LUA_OK) {
        const char *msg = lua_tostring(L, -1);
        say(chunkname + 1);      /* past the = */
        say(": ");
        say((msg != NULL) ? msg : "(no message)");
        say("\n");
        return 1;
    }

    return 0;
}
