/*
 * init: the first Lua process.
 *
 * It sets up the heap the kernel mapped for it, opens a lua_State, and runs
 * a chunk built into the image. There is no filesystem to load one from
 * until M8, and no namespace to ask until M5.
 */

#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include "lua.h"
#include "lauxlib.h"
#include "kosmos.h"
#include "kosmos_lua.h"

/* Generated by tools/bin2c.py from user/init/init.lua. NUL terminated past
 * init_lua_len, so it can be used as a string. */
extern const unsigned char init_lua[];
extern const unsigned long init_lua_len;

#ifdef KOSMOS_TEST
/*
 * The second chunk, in the test image only.
 *
 * `user/tests/luatest.lua` holds the Lua tests that used to run inside the
 * kernel. It is a separate chunk rather than more roles in init.lua because
 * it must not reach the image that ships, and Lua source cannot be compiled
 * out of a chunk the way C can.
 *
 * A boot word at or above LUATEST_BASE selects it. The bases do not overlap,
 * so a role number can only mean one of the two.
 */
extern const unsigned char luatest_lua[];
extern const unsigned long luatest_lua_len;

#define LUATEST_BASE    1000UL
#endif

#ifdef KOSMOS_BENCH
/* The same arrangement for the benchmark image. `user/tests/luabench.lua`
 * measures what Lua costs, out here where Lua runs. */
extern const unsigned char luabench_lua[];
extern const unsigned long luabench_lua_len;

#define LUABENCH_BASE   2000UL
#endif

/*
 * The audio server, which is C and does not want a `lua_State` at all.
 *
 * Dispatched before the interpreter is opened rather than after, and that
 * is the point rather than an optimisation: `CLAUDE.md` says a server runs
 * on behalf of another process and therefore does not get a collector, and
 * the way to mean that is for there to be no collector in the process. A
 * server that merely promises not to allocate is a server somebody adds a
 * `print` to next month.
 */
void audio_server(long endpoint);
void devices_server(long endpoint);
void binfs_server(long endpoint, int libraries);
void appfs_server(long endpoint);
void console_server(long endpoint);

#define ROLE_AUDIO    16UL
#define ROLE_DEVICES   9UL
#define ROLE_BINFS    11UL
#define ROLE_LIBFS    13UL
#define ROLE_APPFS    14UL
#define ROLE_CONSOLE   4UL

static void say(const char *s)
{
    (void)kosmos_write(s, strlen(s));
}

/* What this process calls itself, which is what `procs` and `kill` show. */
static void named(const char *s)
{
    (void)kosmos_setname(s, strlen(s));
}

int main(unsigned long arg)
{
    lua_State *L;
    int status;
    const unsigned char *chunk;
    unsigned long chunk_len;
    const char *chunkname;
    unsigned long base = 0;

    /*
     * The heap is memory the kernel mapped at a fixed address, not memory
     * asked for. A process cannot grow its own heap yet and does not need
     * to: `design.md` §5.2 wants a bounded one anyway, because a small heap
     * collects fast and the maximum GC pause is what decides whether the
     * system stutters.
     */
    heap_init((void *)USER_HEAP, USER_HEAP_SIZE);

    /*
     * Before Lua, and it never comes back.
     *
     * The capability table a spawned process is handed puts its own
     * endpoint first, which is the same arrangement every Lua server here
     * relies on - this one just does not need a chunk loaded to find it.
     */
    /*
     * Each of these says what it is before it starts serving.
     *
     * `sys.name` was a line in every Lua role and went out with them, which
     * nobody noticed until a screenshot of `procs` showed five processes
     * called `init`: a process's name is whatever it last said it was, and a
     * server that says nothing keeps the name of the image it was spawned
     * from. It costs one syscall at startup and it is the only way anything
     * can tell these apart.
     */
    if (arg == ROLE_AUDIO) {
        named("audio");
        audio_server(0);
    }

    if (arg == ROLE_DEVICES) {
        named("devices");
        devices_server(0);
    }

    if (arg == ROLE_BINFS) {
        named("binfs");
        binfs_server(0, 0);
    }

    if (arg == ROLE_LIBFS) {
        named("libfs");
        binfs_server(0, 1);
    }

    if (arg == ROLE_APPFS) {
        named("appfs");
        appfs_server(0);
    }

    if (arg == ROLE_CONSOLE) {
        named("console");
        console_server(0);
    }

    L = kosmos_lua_open();
    if (L == NULL) {
        say("init: no memory for a lua_State\n");
        return 1;
    }

    /*
     * Which chunk, and which role within it.
     *
     * `base` is subtracted from the boot word rather than the chunk being
     * told what it is, so a role number inside a chunk means the same thing
     * whether it arrived from the kernel or from a sibling's spawn.
     */
    chunk = init_lua;
    chunk_len = init_lua_len;
    chunkname = "=init";     /* the leading = is Lua's "this is not a file" */

#ifdef KOSMOS_TEST
    if (arg >= LUATEST_BASE) {
        chunk = luatest_lua;
        chunk_len = luatest_lua_len;
        chunkname = "=luatest";
        base = LUATEST_BASE;
    }
#endif

#ifdef KOSMOS_BENCH
    if (arg >= LUABENCH_BASE) {
        chunk = luabench_lua;
        chunk_len = luabench_lua_len;
        chunkname = "=luabench";
        base = LUABENCH_BASE;
    }
#endif

    /*
     * The boot word reaches the chunk as its `...`, the same way a spawned
     * thread's capability did in the kernel's copy. A process is told one
     * thing and handed a capability table; everything else it works out.
     *
     * The base goes with it, because a chunk that spawns a sibling has to
     * put it back on to name a role in itself.
     */
    status = luaL_loadbufferx(L, (const char *)chunk, chunk_len, chunkname, "t");

    if (status == LUA_OK) {
        lua_pushinteger(L, (lua_Integer)(arg - base));
        lua_pushinteger(L, (lua_Integer)base);
        status = lua_pcall(L, 2, 0, 0);
    }

    if (status != LUA_OK) {
        const char *msg = lua_tostring(L, -1);
        say(chunkname + 1);      /* past the = */
        say(": ");
        say((msg != NULL) ? msg : "(no message)");
        say("\n");
        return 1;
    }

    return 0;
}
