/*
 * init: the first Lua process.
 *
 * It sets up the heap the kernel mapped for it, opens a lua_State, and runs
 * a chunk built into the image. There is no filesystem to load one from
 * until M8, and no namespace to ask until M5.
 */

#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include "lua.h"
#include "lauxlib.h"
#include "kosmos.h"
#include "kosmos_lua.h"

/* Generated by tools/bin2c.py from user/init/init.lua. NUL terminated past
 * init_lua_len, so it can be used as a string. */
extern const unsigned char init_lua[];
extern const unsigned long init_lua_len;

static void say(const char *s)
{
    (void)kosmos_write(s, strlen(s));
}

int main(unsigned long arg)
{
    lua_State *L;
    int status;

    /*
     * The heap is memory the kernel mapped at a fixed address, not memory
     * asked for. A process cannot grow its own heap yet and does not need
     * to: `design.md` §5.2 wants a bounded one anyway, because a small heap
     * collects fast and the maximum GC pause is what decides whether the
     * system stutters.
     */
    heap_init((void *)USER_HEAP, USER_HEAP_SIZE);

    L = kosmos_lua_open();
    if (L == NULL) {
        say("init: no memory for a lua_State\n");
        return 1;
    }

    /*
     * The boot word reaches the chunk as its `...`, the same way a spawned
     * thread's capability does in the kernel's copy. A process is told one
     * thing and handed a capability table; everything else it works out.
     */
    status = luaL_loadbufferx(L, (const char *)init_lua, init_lua_len,
                              "=init", "t");

    if (status == LUA_OK) {
        lua_pushinteger(L, (lua_Integer)arg);
        status = lua_pcall(L, 1, 0, 0);
    }

    if (status != LUA_OK) {
        const char *msg = lua_tostring(L, -1);
        say("init: ");
        say((msg != NULL) ? msg : "(no message)");
        say("\n");
        return 1;
    }

    return 0;
}
