/* Kosmos. Copyright (c) 2026 Diego Cibils. MIT; see LICENSE. */
/*
 * The kernel's output: the serial port always, and the screen when there is
 * one.
 *
 * **On the screen half, and CLAUDE.md's "no graphics in the kernel".** That
 * rule means no graphics *subsystem*: no compositor, no drawing API, no
 * surfaces, no notion of a window. Those live in userland and this file has
 * none of them. What is here is forty lines that put a character into a
 * framebuffer, and it exists for one reason: on a board with no serial cable
 * attached, a boot that says nothing and a panic that prints into the void
 * are the same thing as a machine that does not work. `panic()` writes
 * through here, so it now reaches a screen.
 *
 * That is the same argument that justifies the register dump: diagnostics
 * are not features. The moment anything here starts looking like an API for
 * drawing, it has gone wrong and belongs in `gfx`.
 *
 * The font is the one the user image uses, `assets/fonts/spleen-8x16.bdf`
 * through `tools/bdf2c.py`, linked into both. One font, two renderers - this
 * one for boot and panics, the userland one for the terminal - because they
 * must not depend on each other: the kernel's has to work when there are no
 * processes at all.
 */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "kernel.h"
#include "console.h"
#include "spinlock.h"
#include "hal.h"

/* Generated by tools/bdf2c.py. 16 bytes a glyph, one byte a row, MSB is the
 * leftmost pixel; the glyph after the last is the one for anything the font
 * does not have. */
extern const unsigned char font_8x16[];

/*
 * What each glyph past the unknown box is. `tools/bdf2c.py` emits printable
 * ASCII, then one hollow box, then the Block Elements - which are not
 * contiguous with ASCII and so need saying rather than computing.
 */
extern const unsigned short font_8x16_extra[];
extern const unsigned long  font_8x16_extra_len;

#define GLYPH_W     8
#define GLYPH_H     16
#define GLYPH_FIRST 0x20
#define GLYPH_LAST  0x7e

/*
 * The bottom of the screen belongs to the boot progress bar, and afterwards
 * to whatever userland puts there - the shell's status line lives in the
 * same rows. Text never scrolls through them, which is the whole point: two
 * writers on one framebuffer with no compositor between them works only
 * because these rows are nobody else's.
 *
 * Two rows. Three was a band; this is a line.
 */
#define RESERVED_ROWS   2

/*
 * Written before there is a second thread and read by one thread thereafter.
 * `CLAUDE.md` forbids loose mutable globals for SMP reasons; the console is
 * the exception every kernel makes, and it is the right one - output has to
 * keep working when everything else is already dead, which rules out taking
 * a lock to get at it.
 */
static struct fb   screen;
static bool        attached;

/*
 * Set while something else owns the screen.
 *
 * The kernel console and a compositor cannot both draw on one framebuffer.
 * They were both doing it: printing a line scrolled the whole screen, which
 * dragged a window's pixels up sixteen rows and left a copy of its title bar
 * behind. It looked like a windowing bug and was not - the console's scroll
 * moves every pixel on the display, because as far as it knows every pixel
 * is text.
 *
 * So a process that has taken the screen says so, and from then until it
 * gives it back this console writes to the serial line and nowhere else.
 * Nothing is lost: the cable has always had everything, and a system that
 * can only be debugged through the thing that is currently broken is not
 * one that can be debugged.
 *
 * A panic clears this. Whatever is on the screen matters less than the
 * reason the machine stopped.
 */
static bool        suspended;

/*
 * Everything this console has ever printed, most recent first out.
 *
 * A ring, because the alternative is deciding in advance how much of a
 * boot is worth keeping and being wrong. Sixteen kilobytes is a few hundred
 * lines: enough to hold a whole boot and the last minute of whatever
 * happened after it, and small enough to sit in .bss without anybody
 * noticing.
 *
 * Everything goes through `kputc` - the kernel's own messages and every
 * `sys.write` from every process, because a process prints by asking the
 * console server and the console server calls `sys.write` - so this is one
 * place with all of it, in order, which is exactly what a log viewer needs
 * and what neither the serial line nor the screen can give it after the
 * fact.
 */
/*
 * **16 KB, and it was not "a whole boot" - which is the claim the paragraph
 * above made and the first real machine disproved.**
 *
 * A boot on hardware is the twelve stages, the wordmark, and `neofetch`,
 * and by the time a person can open a window and look, the stages are the
 * part that has already gone past. That is exactly backwards: the boot
 * narration is the most valuable thing in here and the first to be evicted,
 * because a ring evicts by age and the boot is the oldest thing there is.
 *
 * 64 KB holds a boot and a long session after it. It is .bss on a machine
 * with hundreds of megabytes, and the alternative - a person on a laptop
 * with no serial port unable to read why their own machine did something -
 * is not a trade worth 48 kilobytes.
 */
#define LOG_BYTES CONSOLE_LOG_BYTES

static char          logbuf[LOG_BYTES];
static unsigned long logged;            /* total ever written */

/*
 * One question, asked in one place.
 *
 * There were four separate tests of `attached` scattered through this file
 * and adding `suspended` meant finding all of them. Three were found; the
 * fourth was `kputc`, which is the one that actually prints, so a window
 * manager could take the screen and the console would carry on writing over
 * it. The symptom looked exactly like the bug being fixed.
 */
static bool can_draw(void)
{
    return attached && !suspended;
}

/*
 * What was printed before there was a screen.
 *
 * The display cannot be the first thing brought up: it needs the MMU on
 * first, or the framebuffer is Device memory and clearing three megabytes of
 * it is the 10-50x penalty `gfx.md` §19.5 warns about. So the first four
 * stages of the boot happen before there is anywhere to draw them, and
 * without this the screen would start at stage five and the beginning of the
 * boot - the part that says how the machine came up - would exist only on a
 * cable that may not be attached.
 *
 * An earlier comment here argued against exactly this, on the grounds that a
 * buffer which exists to make the start look tidy is a buffer that can
 * overflow during a panic. That was wrong: nothing writes to it once the
 * screen is attached, so a panic never touches it. It is written before
 * there is a second thread and replayed once.
 *
 * Bounded and it drops the oldest rather than growing. If it ever fills, the
 * screen says so instead of quietly showing a boot that began in the middle.
 */
#define EARLY_BYTES 2048

static char        early[EARLY_BYTES];
static unsigned    early_len;
static bool        early_lost;

/*
 * The colours that went with those characters, as runs.
 *
 * Everything printed before the display exists is buffered and replayed on
 * to it when it arrives, and the first version of that replayed in one flat
 * grey - so the first five boot stages were colourless on screen and
 * coloured over the serial line, which is the first thing anybody sees and
 * looks like a bug in the boot log.
 *
 * A run list rather than escape codes in the text. The comment that used to
 * be here called the alternative "an escape language inside a boot log", and
 * it was right to refuse that: this is a colour and a length, appended only
 * when the colour actually changes, and the replay walks it. Sixteen runs is
 * more than the boot log uses; past that the tail replays in the last colour,
 * which is a worse picture and never a wrong one.
 */
#define EARLY_RUNS  32

static struct {
    unsigned long colour;
    unsigned      len;
} early_run[EARLY_RUNS];

static unsigned early_runs;
static unsigned    cols, rows;      /* the text area, in cells */
static unsigned    cx, cy;          /* the cursor, in cells */
static uint32_t    fg = 0xffc9d1d9;
static uint32_t    bg = 0xff0d1117;

/*
 * The cursor.
 *
 * A block drawn over the cell the next character will land in, toggled from
 * the timer tick. It is the one thing on this screen that has to change
 * without anybody printing, which is why it is driven from the tick rather
 * than from kputc.
 *
 * `shown` is what makes it safe to draw text underneath it: every path that
 * writes a cell hides it first, so the block is never left behind as a
 * square of background over a character somebody just printed.
 */
/*
 * A quarter of a second per toggle, so the cursor blinks twice a second.
 *
 * Written as `25` with a comment reading "at 100 Hz" until the tick became
 * 250 Hz for the sound device, at which point it blinked five times a
 * second and looked frantic. The rate is a kernel decision recorded in one
 * place; a second copy of it here is a second thing to remember, and this
 * is what forgetting looks like.
 */
#define CURSOR_TICKS    (TICK_HZ / 4)

static bool         cursor_shown;
static unsigned     cursor_x, cursor_y;
static unsigned     cursor_phase;

static uint32_t *pixel_row(unsigned y)
{
    return (uint32_t *)(void *)((uint8_t *)(void *)screen.pixels
                                + (size_t)y * screen.pitch);
}

static void fill_rect(unsigned x, unsigned y, unsigned w, unsigned h,
                      uint32_t colour)
{
    unsigned j;

    for (j = 0; j < h; j++) {
        uint32_t *p = pixel_row(y + j) + x;
        unsigned i;

        for (i = 0; i < w; i++) {
            p[i] = colour;
        }
    }
}

static void draw_cursor(bool on)
{
    if (!can_draw()) {
        return;
    }

    /* The whole cell, inverted, rather than an underline: it is legible at
     * this size and it does not depend on the glyph underneath it. */
    fill_rect(cursor_x * GLYPH_W, cursor_y * GLYPH_H, GLYPH_W, GLYPH_H,
              on ? fg : bg);
    cursor_shown = on;
}

/* Takes the cursor off the screen before anything is drawn where it is.
 * Without this, printing while it happens to be showing leaves a solid block
 * sitting on top of the character. */
static void hide_cursor(void)
{
    if (cursor_shown) {
        draw_cursor(false);
    }
}

/*
 * Where a codepoint's rows are, in the one font the kernel has.
 *
 * ASCII is arithmetic, and everything else is a search of 32 entries that
 * only a non-ASCII character ever reaches - so the common path is what it
 * always was and the uncommon one costs a walk nobody will measure. A
 * codepoint in neither range gets the hollow box between them, which is the
 * whole point of that glyph: a character the font does not have should look
 * like one.
 */
static unsigned glyph_index(unsigned cp)
{
    unsigned long i;

    if (cp >= GLYPH_FIRST && cp <= GLYPH_LAST) {
        return cp - GLYPH_FIRST;
    }

    for (i = 0; i < font_8x16_extra_len; i++) {
        if (font_8x16_extra[i] == cp) {
            return (unsigned)(GLYPH_LAST - GLYPH_FIRST + 2 + i);
        }
    }

    return (unsigned)(GLYPH_LAST - GLYPH_FIRST + 1);
}

/*
 * What is on the screen, in characters, so that scrolling never has to read
 * the screen back.
 *
 * **This exists because of one measurement on real hardware.** The scroll
 * below used to move pixels: two million reads from the framebuffer and two
 * million writes, for every line. Under QEMU the framebuffer is host memory
 * and that is free. On a laptop it is a graphics aperture across PCIe,
 * where write-combining makes writes cheap and does nothing at all for
 * reads - every one is an uncached round trip. A ThinkPad at 1920x1080 took
 * something close to a fifth of a second per scrolled line, which is a boot
 * log you can watch arrive.
 *
 * So the console keeps its own text and repaints from it. The screen is
 * write-only from here, which is what the memory type it is mapped with is
 * good at.
 *
 * Twelve bytes a cell and a fixed ceiling, because `CLAUDE.md` is clear
 * that the kernel has no allocator: 256 by 96 covers 2048x1536 at this
 * glyph size, and `console_attach_screen` clamps a larger screen to it
 * rather than writing past the end.
 */
#define CELL_COLS   256u
#define CELL_ROWS    96u

struct cell {
    uint32_t cp;
    uint32_t fg;
    uint32_t bg;
};

static struct cell cells[CELL_ROWS][CELL_COLS];

/* Draws one cell in the colours given, and touches nothing else. */
static void paint_glyph(unsigned col, unsigned line, unsigned cp,
                        uint32_t ink, uint32_t paper)
{
    const unsigned char *glyph = font_8x16
                               + (size_t)glyph_index(cp) * GLYPH_H;
    unsigned y;

    for (y = 0; y < GLYPH_H; y++) {
        uint32_t *p = pixel_row(line * GLYPH_H + y) + col * GLYPH_W;
        unsigned bits = glyph[y];
        unsigned x;

        for (x = 0; x < GLYPH_W; x++) {
            p[x] = (bits & (0x80u >> x)) ? ink : paper;
        }
    }
}

static void draw_glyph(unsigned col, unsigned line, unsigned cp)
{
    if (col < CELL_COLS && line < CELL_ROWS) {
        cells[line][col].cp = cp;
        cells[line][col].fg = fg;
        cells[line][col].bg = bg;
    }

    paint_glyph(col, line, cp, fg, bg);
}

/* Everything the grid says, drawn again. Writes only. */
static void repaint(void)
{
    unsigned line, col;

    for (line = 0; line < rows && line < CELL_ROWS; line++) {
        for (col = 0; col < cols && col < CELL_COLS; col++) {
            const struct cell *c = &cells[line][col];

            paint_glyph(col, line, c->cp ? c->cp : ' ', c->fg, c->bg);
        }
    }
}

/* Everything up one line, and the last line cleared. Done a pixel row at a
 * time rather than with memmove because the framebuffer is volatile and
 * casting that away to hand it to the libc is the kind of thing that is
 * correct today and wrong the first time anything else touches it. */
static void scroll(void)
{
    unsigned line, col;
    unsigned last = (rows < CELL_ROWS ? rows : CELL_ROWS) - 1;

    /*
     * In the grid, which is memory, and then painted once - rather than in
     * the framebuffer, which on real hardware is across a bus and cannot be
     * read at any speed worth having. The comment above `struct cell` has
     * the measurement.
     */
    for (line = 0; line < last; line++) {
        for (col = 0; col < CELL_COLS; col++) {
            cells[line][col] = cells[line + 1][col];
        }
    }

    for (col = 0; col < CELL_COLS; col++) {
        cells[last][col].cp = ' ';
        cells[last][col].fg = fg;
        cells[last][col].bg = bg;
    }

    repaint();
}

/*
 * One codepoint on the screen. The serial side never comes through here: it
 * has had the raw bytes already, and whatever is on the other end of the
 * wire decodes UTF-8 better than this can.
 */
static void screen_putc(unsigned c)
{
    hide_cursor();

    if (c == '\r') {
        cx = 0;
        return;
    }

    /*
     * Backspace moves the cursor and draws nothing.
     *
     * It is not a printable character, so without this it fell through to
     * draw_glyph, landed outside 0x20..0x7e and came out as the font's box
     * for "no such glyph" - so every correction while typing left a row of
     * boxes on screen while the serial line, which has understood \b since
     * teletypes, looked perfectly fine.
     *
     * Erasing is not this character's job: the console server sends
     * "\b \b", and the space in the middle is what clears the cell. Doing
     * it here as well would erase the character *before* the one being
     * deleted.
     */
    if (c == '\b') {
        if (cx > 0) {
            cx--;
        }
        return;
    }

    if (c != '\n' && cx >= cols) {
        c = '\n';                   /* wrap, then draw the character below */
    }

    if (c == '\n') {
        cx = 0;
        cy++;

        if (cy >= rows) {
            scroll();
            cy = rows - 1;
        }

        return;
    }

    draw_glyph(cx, cy, c);
    cx++;
}

/*------------------------------------------------------------------------
 * UTF-8, on the way to the screen only.
 *
 * This console took a byte and drew it, so anything outside ASCII arrived as
 * two or three hollow boxes where one character was meant - while the serial
 * line, whose far end decodes UTF-8 itself, showed the character perfectly.
 * The same output looking like two different outputs is the complaint the
 * early-run colour list above was written to answer, in the other direction.
 *
 * A state machine rather than a decoder taking a string, because bytes
 * arrive here one at a time: `kputc` is one character and `kwrite_colour` is
 * a loop over one. The state is two words, and it is safe at file scope for
 * the same reason `cx` and `cy` are - every path into here holds the console
 * lock.
 *
 * **A broken sequence draws the replacement character and then reconsiders
 * the byte that broke it.** Dropping that byte instead would turn one bad
 * byte into a swallowed character after it, which is how a decoder turns a
 * corrupted line into a corrupted screen.
 *
 * Overlong forms are not rejected, and that is a decision rather than an
 * omission. They cannot reach a glyph - the font has 127 and a lookup that
 * misses draws the box - so the check would buy a differently wrong picture
 * rather than a right one, in a console that is deliberately the smallest
 * thing that can show text.
 *----------------------------------------------------------------------*/

#define UTF8_REPLACEMENT  0xfffdu

static unsigned utf8_cp;        /* what has been assembled so far */
static unsigned utf8_left;      /* continuation bytes still wanted */

static void screen_byte(char ch)
{
    unsigned b = (unsigned char)ch;

    if (utf8_left > 0) {
        if ((b & 0xc0u) == 0x80u) {
            utf8_cp = (utf8_cp << 6) | (b & 0x3fu);

            if (--utf8_left == 0) {
                screen_putc(utf8_cp);
            }

            return;
        }

        /* Not a continuation, so the sequence never finished. */
        utf8_left = 0;
        screen_putc(UTF8_REPLACEMENT);
    }

    if (b < 0x80u) {
        screen_putc(b);
    } else if ((b & 0xe0u) == 0xc0u) {
        utf8_cp = b & 0x1fu;
        utf8_left = 1;
    } else if ((b & 0xf0u) == 0xe0u) {
        utf8_cp = b & 0x0fu;
        utf8_left = 2;
    } else if ((b & 0xf8u) == 0xf0u) {
        utf8_cp = b & 0x07u;
        utf8_left = 3;
    } else {
        /* A stray continuation byte, or 0xfe / 0xff, which UTF-8 never
         * uses. */
        screen_putc(UTF8_REPLACEMENT);
    }
}

/*
 * Hands the screen to somebody else, or takes it back.
 *
 * Taking it back repaints: the console has no scrollback, so there is
 * nothing to restore and the honest thing is a clear screen with the cursor
 * at the top. What was there belonged to whoever just gave it up.
 */
void console_screen_suspend(void)
{
    suspended = true;
}

void console_screen_resume(void)
{
    if (!suspended) {
        return;
    }

    suspended = false;

    if (!attached) {
        return;
    }

    fill_rect(0, 0, screen.width, screen.height, bg);
    cx = 0;
    cy = 0;
    cursor_shown = false;
}

void console_tick(void)
{
    if (!can_draw()) {
        return;
    }

    /*
     * Follows the cursor rather than remembering where it was: text may have
     * been printed, or scrolled, since the last tick, and a block left at the
     * old position would be a second cursor that never goes away.
     */
    if (cursor_x != cx || cursor_y != cy) {
        hide_cursor();
        cursor_x = cx;
        cursor_y = cy;
        cursor_phase = 0;
    }

    cursor_phase++;

    if (cursor_phase >= CURSOR_TICKS) {
        cursor_phase = 0;
        draw_cursor(!cursor_shown);
    }
}

/* Straight to the screen, bypassing the serial port. Only for text the
 * serial port has already had. */
static void replay(const char *s)
{
    for (; *s != '\0'; s++) {
        screen_byte(*s);
    }
}

void console_detach_screen(void)
{
    attached = false;
}

void console_rebase_screen(const struct fb *fb)
{
    if (!attached) {
        return;
    }

    /*
     * Geometry unchanged, so the cursor and the character grid carry over
     * untouched. Only the address moves.
     */
    if (fb->width != screen.width || fb->height != screen.height
        || fb->pitch != screen.pitch) {
        return;
    }

    screen.pixels = fb->pixels;
}

void console_attach_screen(const struct fb *fb, const char *title)
{
    screen = *fb;
    cols = fb->width / GLYPH_W;
    rows = fb->height / GLYPH_H;

    /*
     * Clamped to the grid, because the grid is a fixed array and this
     * kernel has no allocator to grow one with. A screen wider than 2048
     * loses the columns past it rather than writing past the end of
     * `cells`, which is the failure worth having.
     */
    if (cols > CELL_COLS) {
        cols = CELL_COLS;
    }

    if (rows > CELL_ROWS + RESERVED_ROWS) {
        rows = CELL_ROWS + RESERVED_ROWS;
    }

    if (rows <= RESERVED_ROWS) {
        return;                     /* too small to be worth using */
    }

    rows -= RESERVED_ROWS;
    cx = 0;
    cy = 0;
    attached = true;

    {
        unsigned line, col;

        for (line = 0; line < CELL_ROWS; line++) {
            for (col = 0; col < CELL_COLS; col++) {
                cells[line][col].cp = ' ';
                cells[line][col].fg = fg;
                cells[line][col].bg = bg;
            }
        }
    }

    fill_rect(0, 0, fb->width, fb->height, bg);

    /*
     * The banner and then everything printed before this moment, on the
     * screen only. Neither can go through kputc: the serial line has already
     * had both, and a second copy there would be worse than a missing one
     * here.
     */
    if (title != NULL) {
        uint32_t was = fg;

        fg = 0xff58a6ff;
        for (; *title != '\0'; title++) {
            screen_byte(*title);
        }
        screen_byte('\n');
        screen_byte('\n');
        fg = was;
    }

    if (early_lost) {
        uint32_t was = fg;

        fg = 0xffd29922;
        replay("[earlier output was lost: the replay buffer filled]\n");
        fg = was;
    }

    /*
     * In the colours it was printed in, walking the run list beside the
     * text. Without this the stages that ran before there was a display are
     * grey on screen and coloured on the serial line, which is the same log
     * looking like two different logs.
     */
    {
        const char *at = early;
        unsigned i;

        for (i = 0; i < early_runs && i < EARLY_RUNS; i++) {
            unsigned n = early_run[i].len;

            console_colour(early_run[i].colour);

            while (n-- > 0 && *at != '\0') {
                screen_byte(*at++);
            }
        }

        /* Whatever ran past the last run, which happens only if the boot log
         * changed more colours than there are runs. */
        console_colour(0xffc9d1d9);
        replay(at);
    }

    /* Nothing writes to it again, and saying so here is what makes it safe
     * for panic() to run through this file. */
    early_len = 0;
}

/*
 * The body, without the lock, so that a caller already holding it can change
 * colour mid-run. `kwrite_colour` is that caller and it is why this is split
 * out; nothing else should need it.
 */
static void colour_locked(unsigned long foreground)
{
    /* A new run in the early buffer, so the replay can put this colour back.
     * Opened even when nothing is printed in it: an empty run costs one slot
     * and reasoning about "was anything printed since" costs more. */
    if (early_len < EARLY_BYTES - 1 && early_runs < EARLY_RUNS
        && (early_runs == 0
            || early_run[early_runs - 1].colour != foreground)) {
        early_run[early_runs].colour = foreground;
        early_run[early_runs].len = 0;
        early_runs++;
    }

    fg = (uint32_t)foreground;
}

void console_colour(unsigned long foreground)
{
    /*
     * Deliberately not locked, and that is not an oversight to fix later.
     * Every caller is the kernel itself during boot, on one core, with the
     * console lock untaken - `console_attach_screen` is one of them, and
     * taking the lock here would be a second acquisition inside whatever
     * called it. The locked path for anything that races is `kwrite_colour`.
     */
    colour_locked(foreground);
}

void console_progress(unsigned done, unsigned total)
{
    unsigned y, h, margin, w, filled;

    if (!can_draw() || total == 0) {
        return;
    }

    /* In the reserved rows at the bottom, so scrolling text never disturbs
     * it and it never has to be redrawn from scratch. */
    margin = GLYPH_W * 2;
    y = (rows * GLYPH_H) + GLYPH_H / 2;
    h = GLYPH_H / 2;
    w = screen.width - margin * 2;

    if (done > total) {
        done = total;
    }

    filled = (unsigned)(((uint64_t)w * done) / total);

    fill_rect(margin, y, w, h, 0xff21262d);                 /* the trough */
    fill_rect(margin, y, filled, h, 0xff3fb950);            /* the fill   */
}

/*
 * The most recent bytes, into a caller's buffer. Returns how many.
 *
 * Most recent rather than oldest: a viewer wants the end of the log, and
 * handing it the beginning would mean it had to read the whole thing to
 * find out what just happened.
 */
size_t console_log(char *out, size_t max)
{
    unsigned long available = (logged < LOG_BYTES) ? logged : LOG_BYTES;
    unsigned long start;
    size_t n;

    if (max > available) {
        max = (size_t)available;
    }

    start = logged - max;

    for (n = 0; n < max; n++) {
        out[n] = logbuf[(start + n) % LOG_BYTES];
    }

    return n;
}

/*
 * The console's lock.
 *
 * **Taken around a whole string, not around a character**, and that is the
 * decision worth recording. The state it protects - the log's write index,
 * the cursor, the early buffer - would be safe either way; what would not be
 * safe is the *output*. Two cores printing a line each, with the lock at the
 * character, produce two interleaved lines and no way to read either.
 *
 * That matters most in exactly the case that made this necessary: a panic
 * prints from whichever core panicked, and `spin_panic` prints from any core
 * at all. A deadlock report is worth nothing if another core is writing
 * through it.
 *
 * So `kputs` and `kputu` hold it for their whole output and call an unlocked
 * worker; the public `kputc` takes it for its one character. No recursion
 * and no recursive lock - just one function that does the work and one lock
 * around whichever caller is bigger.
 */
static struct spinlock console_lock = SPINLOCK("console");

static void putc_locked(char c)
{
    /* Before anything decides where it goes: the log is what was printed,
     * not what happened to reach a screen. */
    logbuf[logged % LOG_BYTES] = c;
    logged++;

    if (c == '\n') {
        hal_putchar('\r');
    }

    hal_putchar(c);

    if (can_draw()) {
        if (c == '\n') {
            screen_byte('\r');
        }

        screen_byte(c);
        return;
    }

    /* No screen yet. Kept, so that when one appears the boot can be shown
     * from its beginning rather than from wherever the display happened to
     * come up. */
    if (early_len < EARLY_BYTES - 1) {
        early[early_len++] = c;
        early[early_len] = '\0';

        /* Charged to the run in force. A new run is opened by
         * console_colour; this only ever extends the last one. */
        if (early_runs > 0) {
            early_run[early_runs - 1].len++;
        }
    } else {
        early_lost = true;
    }
}

void kputc(char c)
{
    unsigned long flags = spin_lock(&console_lock);

    putc_locked(c);
    spin_unlock(&console_lock, flags);
}

/*
 * A run of bytes in one colour. See the note in `console.h` for why the
 * colour is an argument rather than a mode.
 *
 * The colour is put back before the lock is released, so the console's
 * default survives a coloured write and the next caller with no opinion
 * gets what it expects.
 */
void kwrite_colour(const char *s, unsigned long len, unsigned long colour)
{
    unsigned long flags = spin_lock(&console_lock);
    unsigned long was = fg;
    unsigned long i;

    if (colour != 0) {
        colour_locked(colour);
    }

    for (i = 0; i < len; i++) {
        putc_locked(s[i]);
    }

    if (colour != 0) {
        colour_locked(was);
    }

    spin_unlock(&console_lock, flags);
}

void kputs(const char *s)
{
    unsigned long flags = spin_lock(&console_lock);

    for (; *s != '\0'; s++) {
        putc_locked(*s);
    }

    spin_unlock(&console_lock, flags);
}

void kputu(unsigned long v)
{
    /* 20 digits is the widest a 64-bit unsigned gets, plus room to spare.
     * The buffer is filled backwards and then walked out forwards. */
    char buf[24];
    unsigned i = 0;

    unsigned long flags;

    if (v == 0) {
        kputc('0');
        return;
    }

    while (v > 0) {
        buf[i++] = (char)('0' + (v % 10));
        v /= 10;
    }

    /* Through the console rather than hal_putchar, which is what it used to
     * do. Bypassing it was harmless while the serial port was the only sink;
     * with a second one it meant every number the kernel printed was
     * missing from the screen.
     *
     * One hold for the whole number, so two cores cannot interleave digits
     * into a third number that never existed. */
    flags = spin_lock(&console_lock);

    while (i > 0) {
        putc_locked(buf[--i]);
    }

    spin_unlock(&console_lock, flags);
}

void kputx(unsigned long v, unsigned digits)
{
    static const char digit[] = "0123456789abcdef";

    if (digits > 16) {
        digits = 16;
    }

    /* Top nibble first, so no buffer is needed. */
    while (digits > 0) {
        digits--;
        kputc(digit[(v >> (digits * 4)) & 0xf]);
    }
}
