/*
 * The kernel's output: the serial port always, and the screen when there is
 * one.
 *
 * **On the screen half, and CLAUDE.md's "no graphics in the kernel".** That
 * rule means no graphics *subsystem*: no compositor, no drawing API, no
 * surfaces, no notion of a window. Those live in userland and this file has
 * none of them. What is here is forty lines that put a character into a
 * framebuffer, and it exists for one reason: on a board with no serial cable
 * attached, a boot that says nothing and a panic that prints into the void
 * are the same thing as a machine that does not work. `panic()` writes
 * through here, so it now reaches a screen.
 *
 * That is the same argument that justifies the register dump: diagnostics
 * are not features. The moment anything here starts looking like an API for
 * drawing, it has gone wrong and belongs in `gfx`.
 *
 * The font is the one the user image uses, `assets/fonts/spleen-8x16.bdf`
 * through `tools/bdf2c.py`, linked into both. One font, two renderers - this
 * one for boot and panics, the userland one for the terminal - because they
 * must not depend on each other: the kernel's has to work when there are no
 * processes at all.
 */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "console.h"
#include "hal.h"

/* Generated by tools/bdf2c.py. 16 bytes a glyph, one byte a row, MSB is the
 * leftmost pixel; the glyph after the last is the one for anything the font
 * does not have. */
extern const unsigned char font_8x16[];

#define GLYPH_W     8
#define GLYPH_H     16
#define GLYPH_FIRST 0x20
#define GLYPH_LAST  0x7e

/*
 * The bottom of the screen belongs to the boot progress bar, and afterwards
 * to whatever userland puts there - the shell's status line lives in the
 * same rows. Text never scrolls through them, which is the whole point: two
 * writers on one framebuffer with no compositor between them works only
 * because these rows are nobody else's.
 *
 * Two rows. Three was a band; this is a line.
 */
#define RESERVED_ROWS   2

/*
 * Written before there is a second thread and read by one thread thereafter.
 * `CLAUDE.md` forbids loose mutable globals for SMP reasons; the console is
 * the exception every kernel makes, and it is the right one - output has to
 * keep working when everything else is already dead, which rules out taking
 * a lock to get at it.
 */
static struct fb   screen;
static bool        attached;

/*
 * Set while something else owns the screen.
 *
 * The kernel console and a compositor cannot both draw on one framebuffer.
 * They were both doing it: printing a line scrolled the whole screen, which
 * dragged a window's pixels up sixteen rows and left a copy of its title bar
 * behind. It looked like a windowing bug and was not - the console's scroll
 * moves every pixel on the display, because as far as it knows every pixel
 * is text.
 *
 * So a process that has taken the screen says so, and from then until it
 * gives it back this console writes to the serial line and nowhere else.
 * Nothing is lost: the cable has always had everything, and a system that
 * can only be debugged through the thing that is currently broken is not
 * one that can be debugged.
 *
 * A panic clears this. Whatever is on the screen matters less than the
 * reason the machine stopped.
 */
static bool        suspended;

/*
 * One question, asked in one place.
 *
 * There were four separate tests of `attached` scattered through this file
 * and adding `suspended` meant finding all of them. Three were found; the
 * fourth was `kputc`, which is the one that actually prints, so a window
 * manager could take the screen and the console would carry on writing over
 * it. The symptom looked exactly like the bug being fixed.
 */
static bool can_draw(void)
{
    return attached && !suspended;
}

/*
 * What was printed before there was a screen.
 *
 * The display cannot be the first thing brought up: it needs the MMU on
 * first, or the framebuffer is Device memory and clearing three megabytes of
 * it is the 10-50x penalty `gfx.md` §19.5 warns about. So the first four
 * stages of the boot happen before there is anywhere to draw them, and
 * without this the screen would start at stage five and the beginning of the
 * boot - the part that says how the machine came up - would exist only on a
 * cable that may not be attached.
 *
 * An earlier comment here argued against exactly this, on the grounds that a
 * buffer which exists to make the start look tidy is a buffer that can
 * overflow during a panic. That was wrong: nothing writes to it once the
 * screen is attached, so a panic never touches it. It is written before
 * there is a second thread and replayed once.
 *
 * Bounded and it drops the oldest rather than growing. If it ever fills, the
 * screen says so instead of quietly showing a boot that began in the middle.
 */
#define EARLY_BYTES 2048

static char        early[EARLY_BYTES];
static unsigned    early_len;
static bool        early_lost;
static unsigned    cols, rows;      /* the text area, in cells */
static unsigned    cx, cy;          /* the cursor, in cells */
static uint32_t    fg = 0xffc9d1d9;
static uint32_t    bg = 0xff0d1117;

/*
 * The cursor.
 *
 * A block drawn over the cell the next character will land in, toggled from
 * the timer tick. It is the one thing on this screen that has to change
 * without anybody printing, which is why it is driven from the tick rather
 * than from kputc.
 *
 * `shown` is what makes it safe to draw text underneath it: every path that
 * writes a cell hides it first, so the block is never left behind as a
 * square of background over a character somebody just printed.
 */
#define CURSOR_TICKS    25          /* at 100 Hz, twice a second */

static bool         cursor_shown;
static unsigned     cursor_x, cursor_y;
static unsigned     cursor_phase;

static uint32_t *pixel_row(unsigned y)
{
    return (uint32_t *)(void *)((uint8_t *)(void *)screen.pixels
                                + (size_t)y * screen.pitch);
}

static void fill_rect(unsigned x, unsigned y, unsigned w, unsigned h,
                      uint32_t colour)
{
    unsigned j;

    for (j = 0; j < h; j++) {
        uint32_t *p = pixel_row(y + j) + x;
        unsigned i;

        for (i = 0; i < w; i++) {
            p[i] = colour;
        }
    }
}

static void draw_cursor(bool on)
{
    if (!can_draw()) {
        return;
    }

    /* The whole cell, inverted, rather than an underline: it is legible at
     * this size and it does not depend on the glyph underneath it. */
    fill_rect(cursor_x * GLYPH_W, cursor_y * GLYPH_H, GLYPH_W, GLYPH_H,
              on ? fg : bg);
    cursor_shown = on;
}

/* Takes the cursor off the screen before anything is drawn where it is.
 * Without this, printing while it happens to be showing leaves a solid block
 * sitting on top of the character. */
static void hide_cursor(void)
{
    if (cursor_shown) {
        draw_cursor(false);
    }
}

static void draw_glyph(unsigned col, unsigned line, char c)
{
    unsigned index = ((unsigned char)c >= GLYPH_FIRST
                      && (unsigned char)c <= GLYPH_LAST)
                   ? (unsigned)((unsigned char)c - GLYPH_FIRST)
                   : (unsigned)(GLYPH_LAST - GLYPH_FIRST + 1);
    const unsigned char *glyph = font_8x16 + (size_t)index * GLYPH_H;
    unsigned y;

    for (y = 0; y < GLYPH_H; y++) {
        uint32_t *p = pixel_row(line * GLYPH_H + y) + col * GLYPH_W;
        unsigned bits = glyph[y];
        unsigned x;

        for (x = 0; x < GLYPH_W; x++) {
            p[x] = (bits & (0x80u >> x)) ? fg : bg;
        }
    }
}

/* Everything up one line, and the last line cleared. Done a pixel row at a
 * time rather than with memmove because the framebuffer is volatile and
 * casting that away to hand it to the libc is the kind of thing that is
 * correct today and wrong the first time anything else touches it. */
static void scroll(void)
{
    unsigned y;

    for (y = GLYPH_H; y < rows * GLYPH_H; y++) {
        uint32_t *dst = pixel_row(y - GLYPH_H);
        const uint32_t *src = pixel_row(y);
        unsigned x;

        for (x = 0; x < cols * GLYPH_W; x++) {
            dst[x] = src[x];
        }
    }

    fill_rect(0, (rows - 1) * GLYPH_H, cols * GLYPH_W, GLYPH_H, bg);
}

static void screen_putc(char c)
{
    hide_cursor();

    if (c == '\r') {
        cx = 0;
        return;
    }

    /*
     * Backspace moves the cursor and draws nothing.
     *
     * It is not a printable character, so without this it fell through to
     * draw_glyph, landed outside 0x20..0x7e and came out as the font's box
     * for "no such glyph" - so every correction while typing left a row of
     * boxes on screen while the serial line, which has understood \b since
     * teletypes, looked perfectly fine.
     *
     * Erasing is not this character's job: the console server sends
     * "\b \b", and the space in the middle is what clears the cell. Doing
     * it here as well would erase the character *before* the one being
     * deleted.
     */
    if (c == '\b') {
        if (cx > 0) {
            cx--;
        }
        return;
    }

    if (c != '\n' && cx >= cols) {
        c = '\n';                   /* wrap, then draw the character below */
    }

    if (c == '\n') {
        cx = 0;
        cy++;

        if (cy >= rows) {
            scroll();
            cy = rows - 1;
        }

        return;
    }

    draw_glyph(cx, cy, c);
    cx++;
}

/*
 * Hands the screen to somebody else, or takes it back.
 *
 * Taking it back repaints: the console has no scrollback, so there is
 * nothing to restore and the honest thing is a clear screen with the cursor
 * at the top. What was there belonged to whoever just gave it up.
 */
void console_screen_suspend(void)
{
    suspended = true;
}

void console_screen_resume(void)
{
    if (!suspended) {
        return;
    }

    suspended = false;

    if (!attached) {
        return;
    }

    fill_rect(0, 0, screen.width, screen.height, bg);
    cx = 0;
    cy = 0;
    cursor_shown = false;
}

void console_tick(void)
{
    if (!can_draw()) {
        return;
    }

    /*
     * Follows the cursor rather than remembering where it was: text may have
     * been printed, or scrolled, since the last tick, and a block left at the
     * old position would be a second cursor that never goes away.
     */
    if (cursor_x != cx || cursor_y != cy) {
        hide_cursor();
        cursor_x = cx;
        cursor_y = cy;
        cursor_phase = 0;
    }

    cursor_phase++;

    if (cursor_phase >= CURSOR_TICKS) {
        cursor_phase = 0;
        draw_cursor(!cursor_shown);
    }
}

/* Straight to the screen, bypassing the serial port. Only for text the
 * serial port has already had. */
static void replay(const char *s)
{
    for (; *s != '\0'; s++) {
        screen_putc(*s);
    }
}

void console_attach_screen(const struct fb *fb, const char *title)
{
    screen = *fb;
    cols = fb->width / GLYPH_W;
    rows = fb->height / GLYPH_H;

    if (rows <= RESERVED_ROWS) {
        return;                     /* too small to be worth using */
    }

    rows -= RESERVED_ROWS;
    cx = 0;
    cy = 0;
    attached = true;

    fill_rect(0, 0, fb->width, fb->height, bg);

    /*
     * The banner and then everything printed before this moment, on the
     * screen only. Neither can go through kputc: the serial line has already
     * had both, and a second copy there would be worse than a missing one
     * here.
     */
    if (title != NULL) {
        uint32_t was = fg;

        fg = 0xff58a6ff;
        for (; *title != '\0'; title++) {
            screen_putc(*title);
        }
        screen_putc('\n');
        screen_putc('\n');
        fg = was;
    }

    if (early_lost) {
        uint32_t was = fg;

        fg = 0xffd29922;
        replay("[earlier output was lost: the replay buffer filled]\n");
        fg = was;
    }

    /*
     * In one colour, because the buffer holds characters and not the colour
     * changes that went with them. Recording those would mean an escape
     * language inside a boot log, which is a lot of machinery to make four
     * lines match six.
     */
    console_colour(0xffc9d1d9);
    replay(early);

    /* Nothing writes to it again, and saying so here is what makes it safe
     * for panic() to run through this file. */
    early_len = 0;
}

void console_colour(unsigned long foreground)
{
    fg = (uint32_t)foreground;
}

void console_progress(unsigned done, unsigned total)
{
    unsigned y, h, margin, w, filled;

    if (!can_draw() || total == 0) {
        return;
    }

    /* In the reserved rows at the bottom, so scrolling text never disturbs
     * it and it never has to be redrawn from scratch. */
    margin = GLYPH_W * 2;
    y = (rows * GLYPH_H) + GLYPH_H / 2;
    h = GLYPH_H / 2;
    w = screen.width - margin * 2;

    if (done > total) {
        done = total;
    }

    filled = (unsigned)(((uint64_t)w * done) / total);

    fill_rect(margin, y, w, h, 0xff21262d);                 /* the trough */
    fill_rect(margin, y, filled, h, 0xff3fb950);            /* the fill   */
}

void kputc(char c)
{
    if (c == '\n') {
        hal_putchar('\r');
    }

    hal_putchar(c);

    if (can_draw()) {
        if (c == '\n') {
            screen_putc('\r');
        }

        screen_putc(c);
        return;
    }

    /* No screen yet. Kept, so that when one appears the boot can be shown
     * from its beginning rather than from wherever the display happened to
     * come up. */
    if (early_len < EARLY_BYTES - 1) {
        early[early_len++] = c;
        early[early_len] = '\0';
    } else {
        early_lost = true;
    }
}

void kputs(const char *s)
{
    for (; *s != '\0'; s++) {
        kputc(*s);
    }
}

void kputu(unsigned long v)
{
    /* 20 digits is the widest a 64-bit unsigned gets, plus room to spare.
     * The buffer is filled backwards and then walked out forwards. */
    char buf[24];
    unsigned i = 0;

    if (v == 0) {
        kputc('0');
        return;
    }

    while (v > 0) {
        buf[i++] = (char)('0' + (v % 10));
        v /= 10;
    }

    /* Through kputc rather than hal_putchar, which is what it used to do.
     * Bypassing it was harmless while the serial port was the only sink;
     * with a second one it meant every number the kernel printed was
     * missing from the screen. */
    while (i > 0) {
        kputc(buf[--i]);
    }
}

void kputx(unsigned long v, unsigned digits)
{
    static const char digit[] = "0123456789abcdef";

    if (digits > 16) {
        digits = 16;
    }

    /* Top nibble first, so no buffer is needed. */
    while (digits > 0) {
        digits--;
        kputc(digit[(v >> (digits * 4)) & 0xf]);
    }
}
