/* Kosmos. Copyright (c) 2026 Diego Cibils. MIT; see LICENSE. */
/*
 * Where C starts. Called from boot/start.S with the stack set up and .bss
 * zeroed, running privileged on the boot processor.
 */

#include <stddef.h>
#include <stdint.h>

#include "hal.h"
#include "console.h"
#include "trap.h"
#include "pmm.h"
#include "page.h"
#include "mmu.h"
#include "kernel.h"

#include "percpu.h"
#include "smp.h"
#include "thread.h"
#include "sched.h"
#include "ipc.h"
#include "memobj.h"
#include "process.h"
#include "screen.h"
#include "boot.h"
#include "image_sum.h"
#include "cpu.h"
#include "ipc.h"
#include "panic.h"

#ifdef KOSMOS_TEST
#include "test.h"
#endif

/* From build/gen/version.c, generated by the Makefile. */
extern const char kosmos_name[];
extern const char kernel_name[];
extern const char kosmos_version[];
extern const char kosmos_build[];
extern const char kosmos_platform[];

#ifdef KOSMOS_BENCH
#include "bench.h"
#endif

/*
 * The userland image, and the build's own account of what is in it.
 * `tools/bin2c.py` emits all six and says why.
 */
extern const unsigned char init_image[];
extern const unsigned long init_image_len;
extern const unsigned long init_image_sum;
extern const unsigned long init_image_page_bytes;
extern const unsigned long init_image_pages;
extern const unsigned      init_image_page_sum[];

/*
 * **Are these still the bytes the build put there?**
 *
 * Every process on this machine runs out of one blob. `process_create` maps
 * the read-only half of the init image straight out of the kernel's own copy
 * - one set of physical pages for sixteen address spaces - so the code, the
 * fonts and the Lua source of every program in `/lib` and `/bin` are these
 * bytes and no others. No process can write one of them: the mapping is read
 * only, and the pages are below the region the allocator hands out, so
 * nothing the kernel allocates can land on them either.
 *
 * On the ThinkPad they change anyway. `diskfs` dies with a *syntax error*
 * parsing `/lib`, `beep` reported `audio.lua:1: unexpected symbol near '$'`,
 * and a 64 MB loader module makes it happen every time where an 8 MB one
 * mostly does not. Nothing in the failure names memory: what a person sees
 * is a Lua error, on a laptop with no serial port.
 *
 * So the build records a checksum and this asks the question out loud, at
 * two moments - as the loader left it, and again just before init is built
 * from it. Those two answers between them say whether the bytes ever arrived
 * correctly, and if they did, whether this kernel is what spoils them. The
 * page table narrows "changed" to an address, which is the form a memory map
 * can be asked about, and the first sixteen bytes of the first bad page say
 * what is there instead - whether it reads as somebody's DMA, somebody's
 * text, or zeroes.
 *
 * **Asked four times, because a boot of that machine is expensive.** Each
 * one names the stages between it and the last, so a single boot says which
 * of them the bytes changed under rather than three boots bisecting it: the
 * loader's own work, then the page tables, then the drivers and whatever DMA
 * they started, then everything up to init.
 *
 * It costs a pass over the image at each, which is nothing on a machine and
 * about a second under emulation for all four. It stays until this is
 * understood.
 */
static void check_init_image(const char *when)
{
    unsigned long sum = image_sum64(init_image, init_image_len);
    unsigned long base = (unsigned long)(uintptr_t)init_image;
    struct image_sum_walk walk;

    boot_fact_begin();
    kputs("the userland image ");
    kputs(when);
    kputs(": 0x");
    kputx(base, 8);
    kputs("..0x");
    kputx(base + init_image_len, 8);

    if (sum == init_image_sum) {
        kputs(", as the build left it");
        boot_fact_end();
        return;
    }

    walk = image_sum_walk(init_image, init_image_len, init_image_page_bytes,
                          init_image_pages, init_image_page_sum);

    kputs("  ** CHANGED ** wanted 0x");
    kputx(init_image_sum, 16);
    kputs(", holds 0x");
    kputx(sum, 16);
    boot_fact_end();

    boot_fact_begin();
    kputu(walk.bad);
    kputs(" of ");
    kputu(init_image_pages);
    kputs(" pages differ");

    if (walk.bad > 0) {
        unsigned long i;

        /*
         * **Which pages, not only how many.**
         *
         * Sixteen bytes of the first bad page was the wrong thing to print
         * and one boot of the machine proved it: they came back *correct* -
         * the page is wrong somewhere later - so the bytes said nothing and
         * the address said only that a page was bad.
         *
         * The list says what kind of fault it is. Contiguous pages are a
         * block that landed in the wrong place. Scattered ones are not. And
         * a list that *differs between two boots of the same stick* is not
         * a placement fault at all, which is the one question a single
         * number can never answer.
         */
        kputs(", at page");

        for (i = 0; i < walk.listed; i++) {
            kputs(" ");
            kputu(walk.at_page[i]);
        }

        if (walk.listed < walk.bad) {
            kputs(" ...");
        }

        kputs("  (the first at 0x");
        kputx(base + walk.first * init_image_page_bytes, 8);
        kputs(")");
    }

    boot_fact_end();

    /*
     * **And where those bytes came from, asked of the machine itself.**
     *
     * Eleven contiguous pages, at the same place on every boot, already
     * wrong when the trap table is the only thing this kernel has done. So
     * something wrote them before we ran, and the only question left is
     * *what* - which is a question about content, and the content is right
     * here: the whole kernel image and the loader's 64 MB disk are both in
     * memory, identity mapped, at this instant.
     *
     * So the page is hashed and every page-aligned window of both is hashed
     * against it. If those bytes are a copy of something, this names it and
     * the investigation is over in one boot instead of one boot per guess.
     * Eighty megabytes of FNV is a fraction of a second and it only happens
     * on a machine that is already broken.
     *
     * Page-aligned only, deliberately: a copy that landed at a page
     * boundary is the shape a loader produces, and searching every byte
     * offset would be four thousand times the work for the shapes it does
     * not.
     */
    {
        extern char __image_end[];

        unsigned long at = walk.first * init_image_page_bytes;
        unsigned long n = init_image_len - at;
        unsigned want;
        unsigned long disk_base = 0, disk_bytes = 0;
        unsigned long where = 0;
        const char *in = NULL;
        unsigned pass;

        if (n > init_image_page_bytes) {
            n = init_image_page_bytes;
        }

        want = image_sum32(init_image + at, n);

        (void)hal_loader_disk(&disk_base, &disk_bytes);

        for (pass = 0; pass < 2 && in == NULL; pass++) {
            unsigned long from = (pass == 0) ? 0x100000UL : disk_base;
            unsigned long to = (pass == 0)
                               ? (unsigned long)(uintptr_t)__image_end
                               : disk_base + disk_bytes;
            unsigned long scan;

            if (to <= from || to - from < n) {
                continue;
            }

            for (scan = from; scan + n <= to; scan += init_image_page_bytes) {
                if (scan == (unsigned long)(uintptr_t)init_image + at) {
                    continue;           /* itself */
                }

                if (image_sum32((const unsigned char *)scan, n) == want) {
                    where = scan;
                    in = (pass == 0) ? "this kernel's image"
                                     : "the loader's disk";
                    break;
                }
            }
        }

        boot_fact_begin();

        if (in != NULL) {
            kputs("those bytes are a copy of 0x");
            kputx(where, 8);
            kputs(", which is in ");
            kputs(in);
        } else {
            kputs("those bytes are nowhere else in the image or the disk, "
                  "so they were written rather than copied");
        }

        boot_fact_end();
    }
}

void kmain(void)
{
    struct fb fb;
    struct cpu_info cpu;
    bool have_display;

    /*
     * The boot, out loud.
     *
     * Ten stages, each announced before it happens and each followed by the
     * numbers that make it worth watching. This is a system built to be
     * learned from, and almost everything interesting about it happens
     * between the reset vector and the prompt - a boot that prints four
     * lines and drops you at a shell has hidden the entire subject.
     *
     * The order below is not arrangeable. Each stage needs the one above it:
     * there is no output before the UART, no fault report before the vector
     * table, no page tables before an allocator to build them from, and no
     * process before there are threads to run it on.
     */
    /*
     * This core's own state, before anything that could fault.
     *
     * **The first line of the kernel, and it is one store.** `thread_current`
     * reads through `this_cpu`, and the fault handler asks for the current
     * thread on its way to reporting - so if the very first exception
     * arrives before this has run, the report that exists to explain it
     * takes a second fault instead. One line, at the top, and the ordering
     * constraint disappears rather than being documented.
     *
     * `percpu.h` has the rest of it. There is one core, `NR_CPUS` is 1, and
     * nothing behaves differently: this is `docs/smp.md` step one, done
     * while it cannot fail.
     */
    percpu_init(0);

    hal_early_init();
    /*
     * The first thing anybody sees, and the only place the machine says what
     * it is rather than what it is doing. Everything after this line is a
     * stage reporting a fact.
     *
     * The version and the commit are here rather than only in `About
     * Kosmos`, because the first question about a machine that misbehaves is
     * which build it is running, and the answer should be on screen before
     * anything has had a chance to go wrong.
     */
    console_colour(0xff58a6ff);
    kputs("\nWelcome to ");
    kputs(kosmos_name);
    kputc('\n');
    console_colour(0xff8b949e);
    kputs("A microkernel OS with a Lua userland\n");

    /* The kernel says its own name here, and only here, because this is the
     * one moment it is the thing running. Everything after stage 12 is
     * Kosmos - servers, a desktop, applications - and the kernel is the
     * part of it that is not any of those. */
    kputs(kernel_name);
    kputs(" ");
    kputs(kosmos_version);
    kputs("  ");
    kputs(kosmos_build);
    kputs("  ");
    kputs(kosmos_platform);
    kputc('\n');
    console_colour(0xffc9d1d9);
    kputc('\n');
    boot_stage("serial port");
    boot_why("Somewhere to report from, before anything else can fail.");
    boot_fact(hal_console_describe());

    /* Before anything else that could fault. Until this runs, VBAR_EL1 holds
     * whatever the firmware left, and any exception is a jump into nothing. */
    trap_init();
    boot_stage("exception vectors");
    boot_why("Until the trap table is installed, a fault is a silent hang.");
    boot_fact(trap_describe());

    /* First of the two, and here rather than three lines earlier so that a
     * fault while reading 2.8 MB is a report instead of a silent hang. This
     * one is the loader's work and the firmware's: nothing of this kernel
     * has run yet except the trap table. */
    check_init_image("as the loader left it");

    /*
     * And the screen, as early as the board can give one.
     *
     * **This is the whole answer to "a laptop has no serial port".** The
     * display stage is number six, and the three faults that stood between
     * this kernel and its first real machine were at three, four and five -
     * the loader's information structure outside the boot page tables, a
     * subtraction that wrapped, a framebuffer nobody had mapped. Each of
     * them, on that machine, is a black panel and nothing to read.
     *
     * Only a board with a framebuffer the firmware already set up can
     * answer, which is exactly the board that needs it: `hal_fb_early` is
     * false under QEMU's ramfb, where there is a cable instead.
     *
     * `console_attach_screen` replays what has already been printed, so
     * nothing is lost by the screen arriving three lines in rather than at
     * the first instruction.
     */
    bool early_screen = false;

    have_display = hal_fb_early(&fb);

    if (have_display) {
        screen_init(&fb);
        console_attach_screen(&fb, "Kosmos");
    }

    /*
     * Who we are running on, asked of the processor.
     *
     * Before the allocator, because it needs nothing: every value comes out
     * of a system register the architecture requires the core to implement.
     * It is also the single most useful line in the log the first time this
     * boots on something that is not QEMU.
     */
    cpu_identify(&cpu);
    boot_stage("processor");
    boot_why("Asking the core who it is, out of registers every part must have.");

    /*
     * Composed by `arch/<name>/cpu.c` rather than here. This line used to
     * name MIDR_EL1 in a string literal, which made the boot log the last
     * place in `kernel/` that knew which processor it had been written for.
     */
    boot_fact_begin();
    kputs(cpu.vendor_name);
    kputc(' ');
    kputs(cpu.model_name);
    kputc(' ');
    kputs(cpu.revision_text);
    kputs("  (");
    kputs(cpu.id_name);
    kputs(" 0x");
    kputx(cpu.id, 8);
    kputc(')');
    boot_fact_end();

    /*
     * How many processors there are, and how many are being used.
     *
     * **Two numbers, because they are not the same one.** The firmware is
     * asked what the machine has; `NR_CPUS` is what this kernel was built
     * for. Booting a four-core machine and saying "1 processor" would be
     * true about the kernel and a lie about the computer, and the gap is
     * the honest measure of how far `docs/smp.md` has got.
     */
    boot_fact_begin();
    kputu(hal_cpu_count());
    kputs(" processor");

    if (hal_cpu_count() != 1) {
        kputc('s');
    }

    boot_fact_end();

    /*
     * **How many are *given work* is deliberately not said here**, and this
     * line said it for a while and was wrong every time.
     *
     * `thread_cpu_count()` is a policy set from a boot option, and the
     * option is not read until after `smp_start_others()` some three
     * hundred lines below. Reading it at this point in the boot returns the
     * value it has before anything has been decided, which is one - so
     * `make SMPWORK=4 qemu` printed "4 processors, 1 scheduling" while
     * placing threads on all four.
     *
     * A number that is right only in the default configuration is worse
     * than no number, because it is read as a report. It is said once,
     * lower down, at the point where it is known.
     */

    /* One line, not two. `cpu` at the prompt has the longer version,
     * including why the counter is not the core clock. */
    boot_fact_begin();
    kputu(cpu_pa_bits(&cpu));
    kputs("-bit physical addresses, ");
    kputu(cpu_dcache_line(&cpu));
    kputs("-byte cache lines, ");
    kputu(cpu.counter_hz / 1000000);
    kputs(" MHz counter");
    boot_fact_end();

    pmm_init();
    boot_stage("physical memory");
    boot_why("A bitmap of every page: page tables are themselves made of pages.");

    /*
     * **With the address it starts at**, which is not decoration on a PC.
     * `virt` puts RAM at one constant; a PC's usable memory is wherever the
     * firmware left room, and where it begins decides whether the kernel
     * image is inside it. That is a question `pmm_init` answers with a
     * panic, so the number belongs in the log above it rather than in a
     * debugger afterwards.
     */
    boot_fact_begin();
    kputu(pmm_total_pages() * (PAGE_SIZE / 1024) / 1024);
    kputs(" MB of RAM at 0x");
    kputx(pmm_ram_base(), 8);
    kputs(", in ");
    kputu(pmm_total_pages());
    kputs(" pages of ");
    kputu(PAGE_SIZE / 1024);
    kputs(" KB");
    boot_fact_end();

    boot_fact_begin();
    kputu(pmm_total_pages() - pmm_free_pages());
    kputs(" pages already the kernel's: its image, its bitmap and its stacks");
    boot_fact_end();

    /*
     * **And the rest of the loader's map, which nothing above reads.**
     *
     * One region is adopted and every other entry was thrown away at the
     * moment of the walk. That is correct for deciding what to manage and
     * it is why nobody can answer "what does the firmware think is at this
     * address" - which is the first question to ask about memory that is
     * corrupted where nothing should be able to write it.
     *
     * Printed unfiltered and with the loader's own type numbers, because
     * this is a transcript rather than a conclusion. On `virt` the HAL says
     * there is no map and these lines do not appear.
     */
    {
        extern char __image_end[];

        unsigned long kernel_lo = 0x100000UL;
        unsigned long kernel_hi = (unsigned long)(uintptr_t)__image_end;
        unsigned long user_lo = (unsigned long)(uintptr_t)init_image;
        unsigned long user_hi = user_lo + init_image_len;
        unsigned long base, length;
        unsigned type, i, kept, seen = 0;

        kept = hal_memory_entries(&seen);

        if (kept < seen) {
            boot_fact_begin();
            kputs("the loader's map has ");
            kputu(seen);
            kputs(" entries and only ");
            kputu(kept);
            kputs(" were kept  ** THE REST ARE NOT SHOWN **");
            boot_fact_end();
        }

        /*
         * **One line per entry cost more than it was worth, and that is a
         * correction rather than a tidy-up.**
         *
         * The full dump did its job on the first boot of the machine: it
         * established that the T14 reports `0x00100000..0x8e36f000` usable
         * and that nothing reserved is under this kernel. Then it cost
         * twenty-five lines of a screen somebody photographs, and pushed
         * the first two image checks off the top - which are the ones that
         * say whether the bytes arrived wrong or were spoiled here, and
         * therefore the only two that decide anything.
         *
         * A diagnostic that buries the answer it was printed beside is a
         * worse diagnostic. So: the region holding this kernel, the count,
         * and then only the entries worth a line - the ones that are not
         * usable *and* overlap the image, which is the fault this was
         * looking for and is zero lines on a healthy machine.
         */
        for (i = 0; hal_memory_entry(i, &base, &length, &type); i++) {
            unsigned digits = (base + length) > 0xffffffffUL ? 16 : 8;
            bool over = base < kernel_hi && base + length > kernel_lo;

            if (type == 1) {
                if (!over) {
                    continue;
                }

                boot_fact_begin();
                kputs("this kernel is inside the loader's 0x");
                kputx(base, digits);
                kputs("..0x");
                kputx(base + length, digits);
                kputs(" (usable), of ");
                kputu(seen);
                kputs(" entries");
                boot_fact_end();
                continue;
            }

            if (!over) {
                continue;
            }

            boot_fact_begin();
            kputs("the loader's map: 0x");
            kputx(base, digits);
            kputs("..0x");
            kputx(base + length, digits);
            kputs("  type ");
            kputu(type);

            /*
             * **And whether this kernel is sitting on it**, which is the
             * line this whole dump exists to make possible.
             *
             * The image is loaded at a fixed megabyte because that is what
             * a multiboot header asks for, and nothing has ever checked
             * that the firmware agrees the address is ours. Under OVMF it
             * does not: three entries between 0x800000 and 0x900000 come
             * back type 4 - reserved, and to be preserved - and the image
             * runs from 0x100000 to past 0x1300000, straight through them.
             * The userland image's read-only half, which every process on
             * the machine runs out of and none of them can write, is inside
             * that same span.
             *
             * It survives here, so overlapping is not enough on its own.
             * What that says is that under emulation nothing writes those
             * pages after the loader hands over, which is exactly the thing
             * a real machine's firmware does not promise.
             */
            kputs((base < user_hi && base + length > user_lo)
                  ? "  ** UNDER THE USERLAND IMAGE **"
                  : "  ** UNDER THIS KERNEL **");

            boot_fact_end();
        }
    }

    /*
     * **And a disk the loader carried in**, when there is one - printed
     * beside the memory it was kept out of, because on a laptop with no
     * serial port this line is how anybody learns that the loader handed
     * it over. The server that mounts it starts much later, on a screen
     * that has stopped printing boot facts.
     */
    {
        unsigned long disk_base, disk_bytes;

        if (hal_loader_disk(&disk_base, &disk_bytes)) {
            extern char __image_end[];
            unsigned long image_end = (unsigned long)__image_end;

            boot_fact_begin();
            kputs("a disk from the loader: ");
            kputu(disk_bytes / 1024);
            kputs(" KB at 0x");
            kputx(disk_base, 8);
            kputs("..0x");
            kputx(disk_base + disk_bytes, 8);
            kputs(", kept from the allocator");
            boot_fact_end();

            /*
             * **And whether it landed on this kernel.**
             *
             * A loader puts a module where it likes, and nothing here ever
             * checked that "where it likes" is not on top of the image it
             * just loaded. On the ThinkPad a 64 MB module leaves the
             * libraries source unparseable - `sys.libraries()` returns a
             * string Lua will not load - and an 8 MB one at a different
             * address does not, which is exactly the shape of a module
             * sitting on the read-only data.
             *
             * Printed rather than refused, because this line is how anybody
             * finds out: the machine has no serial port, the disk server
             * cannot print, and "ended, code 11" is all there was.
             */
            boot_fact_begin();
            kputs("this kernel is 0x");
            kputx(0x100000UL, 8);
            kputs("..0x");
            kputx(image_end, 8);

            if (disk_base < image_end && disk_base + disk_bytes > 0x100000UL) {
                kputs("  ** THE MODULE OVERLAPS IT **");
            }

            boot_fact_end();
        }
    }

    /*
     * And what the machine had that this kernel cannot reach.
     *
     * **Said out loud because the alternative was not booting at all.** A
     * kernel that identity maps RAM below the region it gives processes
     * cannot describe a laptop's memory, and until this line existed the
     * machine either panicked to a serial port a laptop does not have or -
     * with more than a gigabyte - faulted before there was a screen to
     * fault on. It runs on what it can reach now, and a number that is
     * quietly two per cent of the truth is exactly the kind of thing that
     * has to be printed rather than left to be discovered.
     */
    {
        unsigned long whole;

        if (hal_ram_capped(&whole)) {
            boot_fact_begin();
            kputs("of ");
            kputu(whole / (1024 * 1024));
            kputs(" MB this machine has, that is all this kernel can map: "
                  "RAM is identity mapped below the process region");
            boot_fact_end();
        }
    }

    /* Translation on. Everything above ran with the MMU off, where every
     * access is uncached Device memory. From here the kernel runs cached,
     * .text is read-only, and address 0 and the stack guard have no
     * translation at all. */
    mmu_init();

    /*
     * **Before the next character is printed.**
     *
     * The identity map the early screen was using is gone as of the line
     * above, and the console is still pointing into it. One `kputs` between
     * here and the remap is a fault inside a console write, which blocks on
     * the lock that write is holding: `spinlock: console held by 0, wanted
     * by 0`, for ever, and on a laptop a black screen that cannot even
     * reach a serial port. The first version of this had exactly that gap,
     * three lines wide.
     */
    if (have_display) {
        if (hal_fb_remap(&fb)) {
            screen_init(&fb);
            console_rebase_screen(&fb);
            early_screen = true;
        } else {
            console_detach_screen();
            have_display = false;
        }
    }

    boot_stage("virtual memory");
    boot_why("Translation on; from here the kernel's own code is read-only.");
    boot_fact(mmu_describe());
    boot_fact("page 0 and the stack guards unmapped, so both faults name themselves");

    /* Second of the four. Between this and the first: the allocator chose a
     * region and reserved what was already taken, and the page tables were
     * built over it. Both write to memory chosen from the loader's map. */
    check_init_image("with the page tables built");

    /*
     * The display, if there is one.
     *
     * False is not an error. `make test` boots without `-device ramfb` and
     * a board may have no monitor attached, and a system that cannot come up
     * without a screen is a system that cannot be debugged over a cable.
     */
    /*
     * The screen, for a board that could not give one early.
     *
     * ramfb is that board: the guest allocates the pixels, so there is
     * nothing to ask before `pmm_init`. Here it is an ordinary question with
     * an ordinary answer, and `console_attach_screen` replays the log so far
     * rather than leaving the same log looking like two different ones.
     */
    if (!have_display) {
        have_display = hal_fb_init(&fb);

        if (have_display) {
            /* Remembered, because a process granted the screen needs these
             * pages mapped and hal_fb_init cannot be asked again: it clears
             * the framebuffer. */
            screen_init(&fb);
            console_attach_screen(&fb, "Kosmos");
        }
    }

    if (have_display) {
        console_progress(boot_stages_done(), BOOT_STAGES);
    }

    boot_stage("display");
    boot_why("Asking the firmware for a linear framebuffer, the way the Pi will.");

    if (have_display) {
        boot_fact_begin();
        kputu(fb.width);
        kputc('x');
        kputu(fb.height);
        kputs(", 32-bit XRGB");
        boot_fact_end();

        boot_fact_begin();
        kputs("from ");
        kputs(hal_fb_describe());
        boot_fact_end();

        /*
         * **Which of the two ways the panel got the log**, and it is a fact
         * about this machine rather than a note to the reader.
         *
         * On a board with a serial port the difference is cosmetic. On the
         * one this exists for it is everything: a screen that arrives here
         * has shown nothing at all for stages one to five, and those are
         * where a first boot on unfamiliar firmware fails. Printed so that
         * a regression is a line that changed rather than a picture nobody
         * compared - a harness cannot time this, because the whole boot to
         * here takes under two seconds.
         */
        boot_fact(early_screen
                  ? "the panel has had this log since stage two"
                  : "attached here; everything above it was replayed");

        /*
         * The pitch, and whether it is the number anybody would guess.
         *
         * **This said "padded" whichever it was**, so a 1920x1080 panel
         * handed over by firmware read `7680 bytes a row, not 7680:
         * padded`, which is a boot fact contradicting itself in one line.
         * It was written when ramfb was the only source and ramfb always
         * pads; a loader's framebuffer is whatever the firmware chose.
         *
         * Both halves are worth printing. Padding is the case `gfx.md`
         * exists to protect against, and equality is the more dangerous
         * one, because it is where code that computes `width * 4` works
         * perfectly and keeps working until the machine changes.
         */
        boot_fact_begin();
        kputu(fb.pitch);
        kputs(" bytes a row");

        if (fb.pitch != fb.width * 4) {
            kputs(", not ");
            kputu(fb.width * 4);
            kputs(": padded, so width * 4 shears here and not later");
        } else {
            kputs(", which is width * 4 exactly on this machine "
                  "and is not a thing anything may assume");
        }

        boot_fact_end();
    } else {
        boot_fact("none attached; the serial line is the only console");
    }

    boot_stage("input devices");
    boot_why(hal_input_describe());

    if (hal_keyboard_init()) {
        boot_fact_begin();
        kputs("keyboard: ");
        kputs(hal_keyboard_describe());
        boot_fact_end();
    } else {
        boot_fact("no keyboard; input comes over the serial line");
    }

    /*
     * The tablet is the same kind of device as the keyboard - both answer to
     * virtio's input id - so the only way to tell them apart is to ask each
     * one whether it has absolute axes. Which is why this is one stage and
     * not two: it is one scan.
     */
    if (hal_pointer_init()) {
        struct pointer_state where;

        boot_fact_begin();
        kputs("pointer: ");
        kputs(hal_pointer_describe());

        if (hal_pointer_poll(&where)) {
            kputu(where.max_x);
        }

        boot_fact_end();
    } else {
        boot_fact("no pointer; windows are moved with the keyboard");
    }

    /*
     * Sound, and what a machine turned out to have is worth saying once, at
     * the start - which is why the board is asked to name the device rather
     * than this printing one. On `virt` there is one possible answer and on
     * a PC there are two, an HDA controller and a virtio device, and the
     * three ways a machine can end up silent are worth telling apart.
     *
     * Started at boot rather than when something first wants to play,
     * because the setup is four synchronous control requests and doing them
     * inside the first `beep` would put them on the path with the deadline.
     */
    if (hal_snd_init()) {
        boot_fact_begin();
        kputs("sound: ");
        kputs(hal_snd_describe());
        kputs(", 44100 Hz stereo, ");
        kputu(HAL_SND_PERIOD_FRAMES);
        kputs("-frame periods (");
        kputu(HAL_SND_PERIOD_FRAMES * 1000u / HAL_SND_RATE);
        kputs(" ms), ");
        kputu(HAL_SND_PERIODS);
        kputs(" deep");
        boot_fact_end();
    } else {
        boot_fact_begin();
        kputs("no sound: ");
        kputs(hal_snd_describe());
        boot_fact_end();
    }

    /*
     * And the network card, in the same scan and for the same reason.
     *
     * Brought up at boot rather than when something first wants to send,
     * because the card has to be handed its receive buffers before a frame
     * arrives - a device with nowhere to put one drops it, and the first
     * thing that arrives on a network is usually somebody else's broadcast
     * rather than an answer to us.
     */
    {
        struct netdev card;

        if (hal_net_init(&card)) {
            unsigned i;

            boot_fact_begin();
            kputs("network: virtio-net, ");

            for (i = 0; i < 6; i++) {
                if (i > 0) {
                    kputc(':');
                }

                kputx(card.mac[i], 2);
            }

            kputs(", MTU ");
            kputu(card.mtu);
            boot_fact_end();
        } else {
            boot_fact("no network card; this machine is on its own");
        }
    }

    thread_init();
    boot_stage("threads");
    boot_why("A fixed pool; two stacks each, so a stack overflow can report itself.");

    boot_fact_begin();
    kputu(THREAD_MAX);
    kputs(" slots, two stacks each, a guard page below every one");
    boot_fact_end();

    ipc_init();
    memobj_init();
    boot_stage("IPC and capabilities");
    boot_why("How processes talk, and the only way they can. Nothing is buffered.");

    boot_fact_begin();
    kputu(ENDPOINT_MAX);
    kputs(" endpoints, ");
    kputu(CAPS_PER_THREAD);
    kputs(" capabilities a thread, generation-numbered against reuse");
    boot_fact_end();

    process_init();
    boot_stage("processes");
    boot_why("An address space and a thread at user level; the kernel is mapped, not reachable.");

    boot_fact_begin();
    kputu(PROCESS_MAX);
    kputs(" slots; each gets its own page tables, heap and stack");
    boot_fact_end();

    hal_irq_init();
    hal_timer_init(TICK_HZ);

    /*
     * And now the other processors.
     *
     * **After the interrupt controller and the clock, and this is the one
     * ordering the whole step has.** A secondary's own setup asks the GIC
     * for its redistributor and arms its comparator with the interval
     * `hal_timer_init` just computed, so starting one before this point is
     * starting it into a machine that has neither.
     *
     * It was fifty lines earlier than this, beside the line that counts the
     * processors, where it reads naturally and was wrong twice over: once
     * before `mmu_init`, where the secondaries enabled translation against
     * page tables that did not exist yet and none of them ever arrived; and
     * then here, where they would panic on an interval of zero. Both
     * failures are silent in their own way, which is the argument for the
     * comment rather than the line.
     *
     * Still before `cpu_irq_enable` below, so core zero is not taking
     * interrupts while it waits for them.
     */
    smp_start_others();

    /*
     * How many processors new threads are spread across.
     *
     * **Every one that came up, unless asked for fewer.** It was one by
     * default for months, and that was a policy rather than a limitation:
     * the mechanism worked and the confidence did not. What it waited for
     * arrived one fault at a time - locked drivers, a secondary that
     * preempts, a wake that preempts the right core, a reply not lost
     * between cores, a TLB shootdown on x86 - and then the ThinkPad ran its
     * desktop spread across all eight of its processors with a pointer that
     * did not jump. `docs/smp.md` has the whole account.
     *
     * So a plain boot sets nothing here and `thread_cpu_count` answers
     * `smp_online()`. The option stays, as a way to *narrow*:
     * `opt/kosmos/smp=1` - `make SMPWORK=1 qemu`, or the word on GRUB's
     * line - homes every new thread on core zero again, and `=2` halves the
     * search space when something breaks. It cannot widen past the
     * processors that arrived; `thread_cpu_count` sees to that.
     */
    {
        char value[16];

        if (hal_boot_option("opt/kosmos/smp", value, sizeof(value))) {
            unsigned n = 0;
            unsigned i;

            for (i = 0; value[i] >= '0' && value[i] <= '9'; i++) {
                n = n * 10 + (unsigned)(value[i] - '0');
            }

            thread_place_across(n);
        }
    }

    /*
     * Said only when there is something to say. On a machine with one
     * processor the line would be "1 of them in the kernel", which is the
     * previous line again in different words - and a boot log that repeats
     * itself is one people stop reading.
     */
    if (hal_cpu_count() > 1) {
        boot_fact_begin();
        kputu(smp_online() - 1);
        kputs(" of the others in the kernel too, ticking and idle");

        if (smp_online() < hal_cpu_count()) {
            kputs("; the rest are still in firmware");
        }

        boot_fact_end();

        /*
         * And the placement policy, here because here it is known: the
         * boot option was read a few lines above.
         */
        boot_fact_begin();
        kputu(thread_cpu_count());
        kputs(" of them given new threads");

        if (thread_cpu_count() < smp_online()) {
            kputs("; opt/kosmos/smp asked for fewer");
        }

        boot_fact_end();
    }

    /* Nothing has been able to interrupt this core since start.S masked
     * everything on the way in. Now there is a handler and a source. */
    cpu_irq_enable();

    /* Third of the four, and the one a DMA answer would show up in: between
     * this and the second are the display, the keyboard, the pointer and the
     * storage controller, which are the parts of this kernel that hand a
     * physical address to something that is not the processor. */
    check_init_image("with the devices up");

    boot_stage("timer and interrupts");
    boot_why("The heartbeat: from here a thread that never yields is interrupted.");

    boot_fact_begin();
    kputu(TICK_HZ);
    kputs(" Hz off ");
    kputs(hal_timer_describe());
    boot_fact_end();

    boot_fact_begin();
    kputs("interrupts: ");
    kputs(hal_irq_describe());
    kputs(", scheduling ");
    kputs(sched_current()->name);
    boot_fact_end();

    boot_stage("userland");
    boot_why("The kernel's job ends here: it starts one process and stops.");

    /*
     * In the test and bench images, the suite *is* the userland: it runs
     * here instead of init and never comes back.
     *
     * These two calls were silently deleted by a careless rewrite of this
     * function, and the symptom was not a failure - it was `make test`
     * apparently hanging, because the image booted perfectly into a shell
     * while the host runner sat waiting for a TAP plan that was never
     * coming. The second time a slice-based edit has quietly dropped lines
     * from the middle of something.
     */
#ifdef KOSMOS_TEST
    boot_fact("the test suite, which stands in for init in this image");
    tests_run();        /* never returns: exits the guest through semihosting */
#endif

#ifdef KOSMOS_BENCH
    boot_fact("the benchmarks, which stand in for init in this image");
    bench_run();        /* likewise */
#endif

    boot_fact("init: 1 process, which will become 4");

    /*
     * Start init, and nothing else.
     *
     * The kernel used to create the console server, the ramfs and the shell,
     * and wire their capabilities together. That was init's job being done
     * in the wrong place, and `roadmap.md` says so. Now the kernel makes one
     * process, hands it the console and an endpoint per server it is
     * expected to start, and stops.
     *
     * What init can do is bounded by what it was given. It cannot promote a
     * child beyond itself: a spawn resolves every capability against the
     * parent's own table, and passing on the console is refused unless the
     * parent holds it.
     */
    {
        struct process *init;
        cap_t console_ep = ipc_endpoint_create();
        cap_t ramfs_ep = ipc_endpoint_create();
        cap_t devices_ep = ipc_endpoint_create();
        cap_t binfs_ep = ipc_endpoint_create();

        if (console_ep < 0 || ramfs_ep < 0 || devices_ep < 0 || binfs_ep < 0) {
            panic("no endpoints for init");
        }

        /* And the second, with every stage of this kernel between it and
         * the first: the allocator, the page tables, the display, the
         * input devices, the timer and whatever DMA any of them started. */
        check_init_image("before init is built from it");

        init = process_create("init", init_image,
                              (size_t)init_image_len, 7 /* init */);

        if (init == NULL) {
            panic("could not create init");
        }

        /* It holds the console so it can pass it on, and an endpoint for
         * each server, at the indices it expects them. */
        process_grant_console(init);

        /*
         * And hardware, which is the root of the authority
         * `docs/drivers.md` describes: init can mint a capability naming a
         * device's registers, and hand exactly that one to the driver that
         * needs it. Granted here for the same reason the console is - there
         * is nowhere else it could come from, and authority in this system
         * flows from parent to child and never sideways.
         */
        process_grant_devices(init);

        /*
         * And the screen, for the same reason and with the same rule: a
         * spawn refuses to hand on a device the parent does not hold, so
         * init cannot give the shell a screen it was never given itself.
         *
         * Ignored when it fails. A machine booted without a display is a
         * supported way to run, and init's job is to start the system rather
         * than to insist on a monitor.
         */
        (void)process_grant_screen(init);

        /*
         * And the disk, on the same terms. Ignored when it fails for the
         * same reason as the screen: a machine with no drive attached is a
         * supported way to run, and the disk server started without one
         * answers "there is no disk" perfectly well.
         *
         * Init does not touch a sector. It holds this so it can hand it to
         * exactly one child - the whole of the model is that authority
         * arrives from a parent and never from asking.
         */
        (void)process_grant_disk(init);

        /* And authority over processes, which init hands to the task
         * manager and to nothing else. */
        process_grant_procctl(init);

        /*
         * And the sound device, on the same argument as the screen: init
         * holds every device at boot and hands each on to whoever it
         * decides should have it. False here means the board has none,
         * which is not a failure of anything.
         */
        (void)process_grant_audio(init);

        /*
         * And the network card, on the same terms as the disk: init holds
         * it so it can hand it on, and hands it to exactly one process.
         * Ignored when it fails, because a machine with no card is a machine
         * and everything on it still runs - which is not true of the screen.
         */
        (void)process_grant_net(init);

        /* At the indices init expects them, and checked rather than assumed:
         * a capability that lands one slot over is a server talking to the
         * wrong endpoint, which fails in a way that looks like a protocol
         * bug rather than a wiring one. */
        if (ipc_cap_grant(init->thread, console_ep) != 0
            || ipc_cap_grant(init->thread, ramfs_ep) != 1
            || ipc_cap_grant(init->thread, devices_ep) != 2
            || ipc_cap_grant(init->thread, binfs_ep) != 3) {
            panic("init's capabilities did not land where expected");
        }

        process_start(init);
    }

    /*
     * Nothing left for this thread to do but keep the scheduler company.
     *
     * There is no Lua behind this line any more, and no REPL. Both were in
     * the image long after the prompt moved into a process, kept there by a
     * test suite that drove the kernel through an interpreter; the tests run
     * out at user level now, and the interpreter went with them.
     */
    /* Named as the idle thread, so that every timer tick can tell whether
     * the machine was working or waiting. It is the only thread that runs
     * when there is nothing to do, which is what makes the answer honest. */
    thread_set_idle(thread_current());

    for (;;) {
        /*
         * Yield when somebody wants the CPU, sleep only when nobody does.
         *
         * This used to be an unconditional `thread_yield(); wfi;`, and the
         * cost of that was not visible from anywhere: a thread that yielded
         * switched here, this thread resumed *inside* thread_yield, returned
         * from it, and went straight to sleep - with the other thread sitting
         * in the runqueue, runnable, waiting for the next timer interrupt to
         * wake this one up again.
         *
         * So every yield cost a whole timer period, and an IPC round trip
         * cost two: ten and twenty milliseconds at 100 Hz. A round trip
         * whose own cost is around thirty counter ticks was taking one and a
         * quarter million of them, and nothing said so - the system was
         * simply, uniformly, a thousand times slower than it should be, in a
         * way no benchmark of a single operation could see.
         */
        if (thread_any_ready()) {
            thread_yield();
            continue;
        }

        /*
         * Nothing to run. Interrupts masked across the check and the sleep,
         * because an interrupt landing between them would make a thread
         * runnable and then this would sleep through until the next tick -
         * the same bug in miniature.
         *
         * `wfi` still wakes on a pending interrupt with PSTATE.I set: masking
         * stops the exception being *taken*, not the wakeup. So this sleeps
         * until something happens and then unmasks, which is the point at
         * which the handler runs.
         */
        cpu_irq_disable();

        if (!thread_any_ready()) {
            cpu_wait_for_interrupt();
        }

        cpu_irq_enable();
    }
}
