/*
 * Where C starts. Called from boot/start.S with the stack set up and .bss
 * zeroed, running at EL1 on core 0.
 */

#include <stddef.h>
#include <stdint.h>

#include "hal.h"
#include "console.h"
#include "trap.h"
#include "pmm.h"
#include "page.h"
#include "mmu.h"
#include "kernel.h"

#include "thread.h"
#include "sched.h"
#include "ipc.h"
#include "memobj.h"
#include "process.h"
#include "screen.h"
#include "boot.h"
#include "cpu.h"
#include "ipc.h"
#include "panic.h"

#ifdef KOSMOS_TEST
#include "test.h"
#endif

/* From build/gen/version.c, generated by the Makefile. */
extern const char kosmos_version[];
extern const char kosmos_build[];
extern const char kosmos_platform[];

#ifdef KOSMOS_BENCH
#include "bench.h"
#endif

void kmain(void)
{
    struct fb fb;
    struct cpu_info cpu;
    bool have_display;

    /*
     * The boot, out loud.
     *
     * Ten stages, each announced before it happens and each followed by the
     * numbers that make it worth watching. This is a system built to be
     * learned from, and almost everything interesting about it happens
     * between the reset vector and the prompt - a boot that prints four
     * lines and drops you at a shell has hidden the entire subject.
     *
     * The order below is not arrangeable. Each stage needs the one above it:
     * there is no output before the UART, no fault report before the vector
     * table, no page tables before an allocator to build them from, and no
     * process before there are threads to run it on.
     */
    hal_early_init();
    /*
     * The first thing anybody sees, and the only place the machine says what
     * it is rather than what it is doing. Everything after this line is a
     * stage reporting a fact.
     *
     * The version and the commit are here rather than only in `About
     * Kosmos`, because the first question about a machine that misbehaves is
     * which build it is running, and the answer should be on screen before
     * anything has had a chance to go wrong.
     */
    console_colour(0xff58a6ff);
    kputs("\nWelcome to Kosmos\n");
    console_colour(0xff8b949e);
    kputs("A microkernel OS with a Lua userland\n");
    kputs(kosmos_version);
    kputs("  ");
    kputs(kosmos_build);
    kputs("  ");
    kputs(kosmos_platform);
    kputc('\n');
    console_colour(0xffc9d1d9);
    kputc('\n');
    boot_stage("serial port");
    boot_why("Somewhere to report from, before anything else can fail.");
    boot_fact("PL011 UART at 0x09000000, polled");

    /* Before anything else that could fault. Until this runs, VBAR_EL1 holds
     * whatever the firmware left, and any exception is a jump into nothing. */
    trap_init();
    boot_stage("exception vectors");
    boot_why("Until VBAR_EL1 points at real code, a fault is a silent hang.");
    boot_fact("16 entries at VBAR_EL1, four instructions each");

    /*
     * Who we are running on, asked of the processor.
     *
     * Before the allocator, because it needs nothing: every value comes out
     * of a system register the architecture requires the core to implement.
     * It is also the single most useful line in the log the first time this
     * boots on something that is not QEMU.
     */
    cpu_identify(&cpu);
    boot_stage("processor");
    boot_why("Asking the core who it is, out of registers every part must have.");

    boot_fact_begin();
    kputs(cpu.implementer_name);
    kputc(' ');
    kputs(cpu.part_name);
    kputs(" r");
    kputu(cpu.variant);
    kputc('p');
    kputu(cpu.revision);
    kputs("  (MIDR_EL1 0x");
    kputx(cpu.midr, 8);
    kputc(')');
    boot_fact_end();

    /* One line, not two. `cpu` at the prompt has the longer version,
     * including why the counter is not the core clock. */
    boot_fact_begin();
    kputu(cpu_pa_bits(&cpu));
    kputs("-bit physical addresses, ");
    kputu(cpu_dcache_line(&cpu));
    kputs("-byte cache lines, ");
    kputu(cpu.counter_hz / 1000000);
    kputs(" MHz counter");
    boot_fact_end();

    pmm_init();
    boot_stage("physical memory");
    boot_why("A bitmap of every page: page tables are themselves made of pages.");

    boot_fact_begin();
    kputu(pmm_total_pages() * (PAGE_SIZE / 1024) / 1024);
    kputs(" MB of RAM in ");
    kputu(pmm_total_pages());
    kputs(" pages of ");
    kputu(PAGE_SIZE / 1024);
    kputs(" KB");
    boot_fact_end();

    boot_fact_begin();
    kputu(pmm_total_pages() - pmm_free_pages());
    kputs(" pages already the kernel's: its image, its bitmap and its stacks");
    boot_fact_end();

    /* Translation on. Everything above ran with the MMU off, where every
     * access is uncached Device memory. From here the kernel runs cached,
     * .text is read-only, and address 0 and the stack guard have no
     * translation at all. */
    mmu_init();
    boot_stage("virtual memory");
    boot_why("Translation on; from here the kernel's own code is read-only.");
    boot_fact("4 KB granule, 39-bit addresses, .text read-only");
    boot_fact("page 0 and the stack guards unmapped, so both faults name themselves");

    /*
     * The display, if there is one.
     *
     * False is not an error. `make test` boots without `-device ramfb` and
     * a board may have no monitor attached, and a system that cannot come up
     * without a screen is a system that cannot be debugged over a cable.
     */
    have_display = hal_fb_init(&fb);

    if (have_display) {
        /* Remembered, because a process granted the screen needs these pages
         * mapped and hal_fb_init cannot be asked again: it clears the
         * framebuffer. */
        screen_init(&fb);

        /*
         * And from here the kernel's own output goes to both. Everything
         * already printed above went to the serial port alone, which is why
         * the screen starts at this line rather than at the first - the
         * alternative is buffering the boot log to replay it, and a buffer
         * that exists only to make the start look tidy is a buffer that can
         * overflow during a panic.
         */
        console_attach_screen(&fb, "Kosmos");
        console_progress(boot_stages_done(), BOOT_STAGES);
    }

    boot_stage("display");
    boot_why("Asking the firmware for a linear framebuffer, the way the Pi will.");

    if (have_display) {
        boot_fact_begin();
        kputu(fb.width);
        kputc('x');
        kputu(fb.height);
        kputs(", 32-bit XRGB");
        boot_fact_end();

        boot_fact_begin();
        kputu(fb.pitch);
        kputs(" bytes a row, not ");
        kputu(fb.width * 4);
        kputs(": padded, so width * 4 shears here and not later");
        boot_fact_end();
    } else {
        boot_fact("none attached; the serial line is the only console");
    }

    boot_stage("input devices");
    boot_why("Scanning thirty-two virtio windows; no PCI bus to walk.");

    if (hal_keyboard_init()) {
        boot_fact("keyboard: virtio-input, negotiated and polled like the serial line");
    } else {
        boot_fact("no keyboard; input comes over the serial line");
    }

    /*
     * The tablet is the same kind of device as the keyboard - both answer to
     * virtio's input id - so the only way to tell them apart is to ask each
     * one whether it has absolute axes. Which is why this is one stage and
     * not two: it is one scan.
     */
    if (hal_pointer_init()) {
        struct pointer_state where;

        boot_fact_begin();
        kputs("pointer: virtio-input with absolute axes, reporting 0..");

        if (hal_pointer_poll(&where)) {
            kputu(where.max_x);
        }

        boot_fact_end();
    } else {
        boot_fact("no pointer; windows are moved with the keyboard");
    }

    thread_init();
    boot_stage("threads");
    boot_why("A fixed pool; two stacks each, so a stack overflow can report itself.");

    boot_fact_begin();
    kputu(THREAD_MAX);
    kputs(" slots, two stacks each, a guard page below every one");
    boot_fact_end();

    ipc_init();
    memobj_init();
    boot_stage("IPC and capabilities");
    boot_why("How processes talk, and the only way they can. Nothing is buffered.");

    boot_fact_begin();
    kputu(ENDPOINT_MAX);
    kputs(" endpoints, ");
    kputu(CAPS_PER_THREAD);
    kputs(" capabilities a thread, generation-numbered against reuse");
    boot_fact_end();

    process_init();
    boot_stage("processes");
    boot_why("An address space and a thread at EL0; the kernel is mapped, not reachable.");

    boot_fact_begin();
    kputu(PROCESS_MAX);
    kputs(" slots; each gets its own page tables, heap and stack");
    boot_fact_end();

    hal_irq_init();
    hal_timer_init(TICK_HZ);

    /* Nothing has been able to interrupt this core since start.S masked
     * everything on the way into EL1. Now there is a handler and a source. */
    __asm__ volatile("msr daifclr, #2" ::: "memory");

    boot_stage("timer and interrupts");
    boot_why("The heartbeat: from here a thread that never yields is interrupted.");

    boot_fact_begin();
    kputu(TICK_HZ);
    kputs(" Hz off the generic timer through a GICv3, scheduling ");
    kputs(sched_current()->name);
    boot_fact_end();

    boot_stage("userland");
    boot_why("The kernel's job ends here: it starts one process and stops.");

    /*
     * In the test and bench images, the suite *is* the userland: it runs
     * here instead of init and never comes back.
     *
     * These two calls were silently deleted by a careless rewrite of this
     * function, and the symptom was not a failure - it was `make test`
     * apparently hanging, because the image booted perfectly into a shell
     * while the host runner sat waiting for a TAP plan that was never
     * coming. The second time a slice-based edit has quietly dropped lines
     * from the middle of something.
     */
#ifdef KOSMOS_TEST
    boot_fact("the test suite, which stands in for init in this image");
    tests_run();        /* never returns: exits the guest through semihosting */
#endif

#ifdef KOSMOS_BENCH
    boot_fact("the benchmarks, which stand in for init in this image");
    bench_run();        /* likewise */
#endif

    boot_fact("init: 1 process, which will become 4");

    /*
     * Start init, and nothing else.
     *
     * The kernel used to create the console server, the ramfs and the shell,
     * and wire their capabilities together. That was init's job being done
     * in the wrong place, and `roadmap.md` says so. Now the kernel makes one
     * process, hands it the console and an endpoint per server it is
     * expected to start, and stops.
     *
     * What init can do is bounded by what it was given. It cannot promote a
     * child beyond itself: a spawn resolves every capability against the
     * parent's own table, and passing on the console is refused unless the
     * parent holds it.
     */
    {
        extern const unsigned char init_image[];
        extern const unsigned long init_image_len;
        struct process *init;
        cap_t console_ep = ipc_endpoint_create();
        cap_t ramfs_ep = ipc_endpoint_create();
        cap_t devices_ep = ipc_endpoint_create();
        cap_t binfs_ep = ipc_endpoint_create();

        if (console_ep < 0 || ramfs_ep < 0 || devices_ep < 0 || binfs_ep < 0) {
            panic("no endpoints for init");
        }

        init = process_create("init", init_image,
                              (size_t)init_image_len, 7 /* init */);

        if (init == NULL) {
            panic("could not create init");
        }

        /* It holds the console so it can pass it on, and an endpoint for
         * each server, at the indices it expects them. */
        process_grant_console(init);

        /*
         * And the screen, for the same reason and with the same rule: a
         * spawn refuses to hand on a device the parent does not hold, so
         * init cannot give the shell a screen it was never given itself.
         *
         * Ignored when it fails. A machine booted without a display is a
         * supported way to run, and init's job is to start the system rather
         * than to insist on a monitor.
         */
        (void)process_grant_screen(init);

        /*
         * And the disk, on the same terms. Ignored when it fails for the
         * same reason as the screen: a machine with no drive attached is a
         * supported way to run, and the disk server started without one
         * answers "there is no disk" perfectly well.
         *
         * Init does not touch a sector. It holds this so it can hand it to
         * exactly one child - the whole of the model is that authority
         * arrives from a parent and never from asking.
         */
        (void)process_grant_disk(init);

        /* At the indices init expects them, and checked rather than assumed:
         * a capability that lands one slot over is a server talking to the
         * wrong endpoint, which fails in a way that looks like a protocol
         * bug rather than a wiring one. */
        if (ipc_cap_grant(init->thread, console_ep) != 0
            || ipc_cap_grant(init->thread, ramfs_ep) != 1
            || ipc_cap_grant(init->thread, devices_ep) != 2
            || ipc_cap_grant(init->thread, binfs_ep) != 3) {
            panic("init's capabilities did not land where expected");
        }

        process_start(init);
    }

    /*
     * Nothing left for this thread to do but keep the scheduler company.
     *
     * There is no Lua behind this line any more, and no REPL. Both were in
     * the image long after the prompt moved into a process, kept there by a
     * test suite that drove the kernel through an interpreter; the tests run
     * at EL0 now and the interpreter went with them.
     */
    /* Named as the idle thread, so that every timer tick can tell whether
     * the machine was working or waiting. It is the only thread that runs
     * when there is nothing to do, which is what makes the answer honest. */
    thread_set_idle(thread_current());

    for (;;) {
        /*
         * Yield when somebody wants the CPU, sleep only when nobody does.
         *
         * This used to be an unconditional `thread_yield(); wfi;`, and the
         * cost of that was not visible from anywhere: a thread that yielded
         * switched here, this thread resumed *inside* thread_yield, returned
         * from it, and went straight to sleep - with the other thread sitting
         * in the runqueue, runnable, waiting for the next timer interrupt to
         * wake this one up again.
         *
         * So every yield cost a whole timer period, and an IPC round trip
         * cost two: ten and twenty milliseconds at 100 Hz. A round trip
         * whose own cost is around thirty counter ticks was taking one and a
         * quarter million of them, and nothing said so - the system was
         * simply, uniformly, a thousand times slower than it should be, in a
         * way no benchmark of a single operation could see.
         */
        if (thread_any_ready()) {
            thread_yield();
            continue;
        }

        /*
         * Nothing to run. Interrupts masked across the check and the sleep,
         * because an interrupt landing between them would make a thread
         * runnable and then this would sleep through until the next tick -
         * the same bug in miniature.
         *
         * `wfi` still wakes on a pending interrupt with PSTATE.I set: masking
         * stops the exception being *taken*, not the wakeup. So this sleeps
         * until something happens and then unmasks, which is the point at
         * which the handler runs.
         */
        __asm__ volatile("msr daifset, #2" ::: "memory");

        if (!thread_any_ready()) {
            __asm__ volatile("wfi");
        }

        __asm__ volatile("msr daifclr, #2" ::: "memory");
    }
}
