#!/usr/bin/env python3
"""
The files in assets/images/, as one C table.

Binary, so unlike programs and libraries these cannot travel as Lua source:
a PNG contains every byte value there is, including the ones that would end
a Lua long string early. They go out as arrays of unsigned char, with a
table of name, pointer and length beside them.

Usage: assets2c.py <symbol> <out.c> <file>...
"""

import os
import sys


def licence_for(path):
    """The licence file sitting beside a vendored file, if there is one.

    The rule in CLAUDE.md is that anything vendored records its licence
    beside it and the generated file repeats the notice. This is the half
    that finds it: `IBMPlexMono-Regular.ttf` is covered by
    `LICENSE.IBMPlexMono`, matched on the part of the name before the first
    `-` or `.`, which is how these files are actually named.

    Returning None is not an error here - it is a fact reported to whoever
    is reading the build, because a vendored file with no licence beside it
    is a thing somebody has to decide about, not a thing this script can
    decide.
    """
    folder = os.path.dirname(path) or "."
    stem = os.path.basename(path)

    for sep in ("-", "."):
        if sep in stem:
            stem = stem.split(sep)[0]

    for entry in sorted(os.listdir(folder)):
        if not entry.startswith("LICENSE"):
            continue

        if entry.lower().endswith("." + stem.lower()):
            return entry

    #
    # Failing that, a licence that covers the whole directory.
    #
    # `assets/fonts/` holds several unrelated fonts under different terms,
    # so each one names its own; `assets/icons/` holds one release of one
    # icon theme under a single notice, and asking Tango to ship seven
    # copies of the same sentence - one per file, named after the file -
    # would mean renaming what it released, which is the one thing the rule
    # about vendored data forbids.
    #
    # So: exactly one LICENSE* in the directory covers everything in it.
    # Two, and it is ambiguous and this says nothing rather than guessing.
    #
    licences = [e for e in sorted(os.listdir(folder))
                if e.startswith("LICENSE")]

    if len(licences) == 1:
        return licences[0]

    return None


def main():
    if len(sys.argv) < 3:
        raise SystemExit(__doc__.strip().splitlines()[-1])

    symbol, out_path, files = sys.argv[1], sys.argv[2], sys.argv[3:]
    files = sorted(files)

    # Who wrote each of these and under what terms, repeated here because
    # the generated file is the one that ends up in the binary and it
    # should not be silent about what it carries.
    licences = {path: licence_for(path) for path in files}
    unlicensed = [p for p, l in licences.items() if l is None]

    lines = [
        "/*",
        f" * Generated by tools/assets2c.py from {len(files)} file(s). Do not edit.",
        " *",
        " * These are vendored files, byte for byte as their authors shipped",
        " * them, and each is covered by the licence named beside it:",
        " *",
    ]

    for path in files:
        beside = licences[path]
        where = os.path.join(os.path.dirname(path) or ".", beside) if beside \
            else "NO LICENCE FILE BESIDE IT"
        lines.append(f" *   {os.path.basename(path)}")
        lines.append(f" *     {where}")

    lines += [
        " */",
        "",
        "#include <stddef.h>",
        "",
    ]

    for n, path in enumerate(files):
        with open(path, "rb") as f:
            data = f.read()

        lines.append(f"/* {path}, {len(data)} bytes */")
        lines.append(f"static const unsigned char asset_{n}[] = {{")

        for at in range(0, len(data), 16):
            row = ", ".join(f"0x{b:02x}" for b in data[at:at + 16])
            lines.append(f"    {row},")

        lines.append("};")
        lines.append("")

    lines.append("struct kosmos_asset {")
    lines.append("    const char          *name;")
    lines.append("    const unsigned char *bytes;")
    lines.append("    size_t               length;")
    lines.append("};")
    lines.append("")
    lines.append(f"const struct kosmos_asset {symbol}[] = {{")

    for n, path in enumerate(files):
        name = os.path.basename(path)
        lines.append(f'    {{ "{name}", asset_{n}, sizeof(asset_{n}) }},')

    lines.append("    { NULL, NULL, 0 },")
    lines.append("};")
    lines.append("")

    with open(out_path, "w") as f:
        f.write("\n".join(lines))

    total = sum(os.path.getsize(p) for p in files)
    print(f"{out_path}: {len(files)} asset(s), {total} bytes")

    # Said out loud rather than left in a comment nobody opens. Not fatal:
    # a person mid-experiment with a font they just downloaded should not
    # have their build stop. It is fatal at the point it would be published,
    # which is a decision for whoever commits it.
    for path in unlicensed:
        print(f"  WARNING: {path} has no licence file beside it. "
              f"CLAUDE.md says vendored data records its licence; this one "
              f"does not, so it should not be committed as it stands.",
              file=sys.stderr)


if __name__ == "__main__":
    main()
