#!/usr/bin/env python3
"""
The files in assets/images/, as one C table.

Binary, so unlike programs and libraries these cannot travel as Lua source:
a PNG contains every byte value there is, including the ones that would end
a Lua long string early. They go out as arrays of unsigned char, with a
table of name, pointer and length beside them.

Usage: assets2c.py <symbol> <out.c> <file>...
"""

import os
import sys


def main():
    if len(sys.argv) < 3:
        raise SystemExit(__doc__.strip().splitlines()[-1])

    symbol, out_path, files = sys.argv[1], sys.argv[2], sys.argv[3:]
    files = sorted(files)

    lines = [
        "/*",
        f" * Generated by tools/assets2c.py from {len(files)} file(s). Do not edit.",
        " */",
        "",
        "#include <stddef.h>",
        "",
    ]

    for n, path in enumerate(files):
        with open(path, "rb") as f:
            data = f.read()

        lines.append(f"/* {path}, {len(data)} bytes */")
        lines.append(f"static const unsigned char asset_{n}[] = {{")

        for at in range(0, len(data), 16):
            row = ", ".join(f"0x{b:02x}" for b in data[at:at + 16])
            lines.append(f"    {row},")

        lines.append("};")
        lines.append("")

    lines.append("struct kosmos_asset {")
    lines.append("    const char          *name;")
    lines.append("    const unsigned char *bytes;")
    lines.append("    size_t               length;")
    lines.append("};")
    lines.append("")
    lines.append(f"const struct kosmos_asset {symbol}[] = {{")

    for n, path in enumerate(files):
        name = os.path.basename(path)
        lines.append(f'    {{ "{name}", asset_{n}, sizeof(asset_{n}) }},')

    lines.append("    { NULL, NULL, 0 },")
    lines.append("};")
    lines.append("")

    with open(out_path, "w") as f:
        f.write("\n".join(lines))

    total = sum(os.path.getsize(p) for p in files)
    print(f"{out_path}: {len(files)} asset(s), {total} bytes")


if __name__ == "__main__":
    main()
