#!/usr/bin/env python3
"""
Small files carried inside the image, as one C table.

Binary, so unlike programs and libraries these cannot travel as Lua source:
a PNG contains every byte value there is, including the ones that would end
a Lua long string early. They go out as arrays of unsigned char, with a
table of name, pointer and length beside them.

Not all of them are pictures and not all of them are vendored - the ASCII
banner is the project's own text - so a file with no licence beside it is
reported and not refused. See `licence_for`.

Usage: assets2c.py <symbol> <out.c> [--prefix=<text>] <file>...

`--prefix` goes in front of the names of the files after it: the wallpapers
are `wallpaper/<file>`, so a caller that lists what the image carries can
tell a picture meant for the desktop from a test pattern without a second
list. It may come more than once, each applying until the next: Haiku's
icons at 16 and 64 are `16x16/<file>` and `64x64/<file>` beside the 32s,
which have no prefix, and two files that would share a name are refused.
"""

import os
import sys


def licence_for(path):
    """The licence file sitting beside a vendored file, if there is one.

    The rule in CLAUDE.md is that anything vendored records its licence
    beside it and the generated file repeats the notice. This is the half
    that finds it: `IBMPlexMono-Regular.ttf` is covered by
    `LICENSE.IBMPlexMono`, matched on the part of the name before the first
    `-` or `.`, which is how these files are actually named.

    Returning None is not an error here - it is a fact reported to whoever
    is reading the build, because a vendored file with no licence beside it
    is a thing somebody has to decide about, not a thing this script can
    decide.
    """
    folder = os.path.dirname(path) or "."
    stem = os.path.basename(path)

    for sep in ("-", "."):
        if sep in stem:
            stem = stem.split(sep)[0]

    for entry in sorted(os.listdir(folder)):
        if not entry.startswith("LICENSE"):
            continue

        if entry.lower().endswith("." + stem.lower()):
            return entry

    #
    # Failing that, a licence that covers the whole directory.
    #
    # `assets/fonts/` holds several unrelated fonts under different terms,
    # so each one names its own; `assets/icons/` holds one release of one
    # icon set under a single notice, and asking Haiku to ship forty-eight
    # copies of the same sentence - one per file, named after the file -
    # would mean renaming what it released, which is the one thing the rule
    # about vendored data forbids.
    #
    # So: exactly one LICENSE* in the directory covers everything in it.
    # Two, and it is ambiguous and this says nothing rather than guessing.
    #
    licences = [e for e in sorted(os.listdir(folder))
                if e.startswith("LICENSE")]

    if len(licences) == 1:
        return licences[0]

    return None


# The line every file this project writes opens with (CLAUDE.md), and no
# vendored file does.
OWN = b"Kosmos. Copyright (c) 2026 Diego Cibils. MIT; see LICENSE."


def own_work(path):
    """True when the file says on its first lines that it is Kosmos's own.

    Its terms are then LICENSE's at the root, and a licence file beside it
    would be a second copy of them. Without this, the tutorial's pages and
    the cheat sheet were each reported as vendored data with no licence -
    a warning that said "should not be committed" about the project's own
    writing, which teaches whoever reads the build to skip warnings.
    """
    with open(path, "rb") as f:
        return OWN in f.read(512)


def main():
    if len(sys.argv) < 3:
        raise SystemExit(__doc__.strip().splitlines()[-1])

    symbol, out_path, args = sys.argv[1], sys.argv[2], sys.argv[3:]
    prefix = ""
    named = {}

    for arg in args:
        if arg.startswith("--prefix="):
            prefix = arg[len("--prefix="):]
        else:
            named[arg] = prefix + os.path.basename(arg)

    if len(set(named.values())) != len(named):
        seen = {}

        for path, name in sorted(named.items()):
            if name in seen:
                raise SystemExit(f"assets2c: {path} and {seen[name]} would "
                                 f"both be called {name}")

            seen[name] = path

    files = sorted(named)

    # Who wrote each of these and under what terms, repeated here because
    # the generated file is the one that ends up in the binary and it
    # should not be silent about what it carries.
    own = {path for path in files if own_work(path)}
    licences = {path: None if path in own else licence_for(path) for path in files}
    unlicensed = [p for p, l in licences.items() if l is None and p not in own]

    lines = [
        "/*",
        f" * Generated by tools/assets2c.py from {len(files)} file(s). Do not edit.",
        " *",
        " * Most of these are vendored files, byte for byte as their authors",
        " * shipped them, each covered by the licence named beside it. The",
        " * project's own say so on their first line and are under LICENSE",
        " * at the root. One that is neither is reported rather than treated",
        " * as an error.",
        " *",
        " *",
    ]

    for path in files:
        beside = licences[path]
        if path in own:
            where = "LICENSE, the project's own, as its first line says"
        elif beside:
            where = os.path.join(os.path.dirname(path) or ".", beside)
        else:
            where = "NO LICENCE FILE BESIDE IT"
        lines.append(f" *   {os.path.basename(path)}")
        lines.append(f" *     {where}")

    lines += [
        " */",
        "",
        "#include <stddef.h>",
        "",
    ]

    for n, path in enumerate(files):
        with open(path, "rb") as f:
            data = f.read()

        lines.append(f"/* {path}, {len(data)} bytes */")
        lines.append(f"static const unsigned char asset_{n}[] = {{")

        for at in range(0, len(data), 16):
            row = ", ".join(f"0x{b:02x}" for b in data[at:at + 16])
            lines.append(f"    {row},")

        lines.append("};")
        lines.append("")

    lines.append("struct kosmos_asset {")
    lines.append("    const char          *name;")
    lines.append("    const unsigned char *bytes;")
    lines.append("    size_t               length;")
    lines.append("};")
    lines.append("")
    lines.append(f"const struct kosmos_asset {symbol}[] = {{")

    for n, path in enumerate(files):
        name = named[path]
        lines.append(f'    {{ "{name}", asset_{n}, sizeof(asset_{n}) }},')

    lines.append("    { NULL, NULL, 0 },")
    lines.append("};")
    lines.append("")

    with open(out_path, "w") as f:
        f.write("\n".join(lines))

    total = sum(os.path.getsize(p) for p in files)
    print(f"{out_path}: {len(files)} asset(s), {total} bytes")

    # Said out loud rather than left in a comment nobody opens. Not fatal:
    # a person mid-experiment with a font they just downloaded should not
    # have their build stop. It is fatal at the point it would be published,
    # which is a decision for whoever commits it.
    for path in unlicensed:
        print(f"  WARNING: {path} has no licence file beside it. "
              f"CLAUDE.md says vendored data records its licence; this one "
              f"does not, so it should not be committed as it stands.",
              file=sys.stderr)


if __name__ == "__main__":
    main()
