#!/usr/bin/env python3
"""
A BDF bitmap font, as a C array.

BDF is the interchange format every bitmap font is distributed in: plain
text, one hex byte per pixel row, and simple enough that parsing it is
cheaper than depending on a library to. The font is vendored unmodified
under assets/fonts/ for the same reason `lua/upstream/` is - the thing in
the tree should be what the author shipped, and anything we do to it should
be a build step that can be read.

The output is the layout the hardware wants and every 8x16 font uses:

    one byte per row, sixteen rows per glyph, MSB is the leftmost pixel

so glyph `c` starts at (c - first) * height and row `r` of it is one byte
whose bit 0x80 is the pixel at x = 0. That is the VGA ROM layout, and it is
what makes the rasteriser a shift and a test rather than a lookup.

Only the printable ASCII range is emitted. The font has a thousand glyphs;
carrying all of them would be sixteen kilobytes for a system that cannot yet
type anything outside 0x20 to 0x7e. When there is a terminal that can, the
range widens here and nothing else changes.

A final glyph is appended for anything outside the range: a hollow box, so a
character the font does not have is visibly a character the font does not
have rather than a space.

Usage: bdf2c.py <font.bdf> <symbol> <out.c>
"""

import re
import sys


def parse(path):
    """Every glyph in the file, as {codepoint: [row bytes]}.

    BDF puts the width in FONTBOUNDINGBOX and per-glyph in BBX, and pads each
    row to a whole number of bytes. Only 8-pixel-wide fonts are accepted, so
    a row is exactly one byte and there is no padding to reason about - a
    wider font would need the rows unpacked, and silently taking the first
    byte of each would produce a font that is subtly wrong rather than one
    that fails.
    """
    glyphs = {}
    codepoint = None
    rows = None

    with open(path, errors="replace") as f:
        for line in f:
            line = line.strip()

            if line.startswith("FONTBOUNDINGBOX"):
                width = int(line.split()[1])
                if width != 8:
                    raise SystemExit(
                        f"{path}: this converter only handles 8-pixel-wide "
                        f"fonts, and this one is {width}. A wider one packs "
                        f"each row into more than a byte and needs unpacking."
                    )

            elif line.startswith("ENCODING "):
                codepoint = int(line.split()[1])

            elif line == "BITMAP":
                rows = []

            elif line == "ENDCHAR":
                if codepoint is not None and rows is not None:
                    glyphs[codepoint] = rows
                codepoint, rows = None, None

            elif rows is not None and re.fullmatch(r"[0-9A-Fa-f]+", line):
                rows.append(int(line[:2], 16))

    return glyphs


def provenance(path):
    """The COMMENT block at the top, which is where the font says who it is."""
    out = []

    with open(path, errors="replace") as f:
        for line in f:
            if line.startswith("COMMENT"):
                text = line[len("COMMENT"):].strip()
                if text and text not in ("/*", "*/"):
                    out.append(text.lstrip("* ").rstrip())
            elif line.startswith("FONT ") or out and not line.startswith("COMMENT"):
                if line.startswith("FONT "):
                    out.append(line.strip())
                break

    return [l for l in out if l]


FIRST, LAST, HEIGHT = 0x20, 0x7E, 16

# A hollow box, for anything the font does not have. Deliberately not a
# space: a missing character should look missing.
UNKNOWN = [0x00, 0x00, 0x7E, 0x42, 0x42, 0x42, 0x42, 0x42,
           0x42, 0x42, 0x42, 0x7E, 0x00, 0x00, 0x00, 0x00]


def main():
    if len(sys.argv) != 4:
        raise SystemExit(__doc__.strip().splitlines()[-1])

    source, symbol, out = sys.argv[1], sys.argv[2], sys.argv[3]
    glyphs = parse(source)

    missing = [c for c in range(FIRST, LAST + 1) if c not in glyphs]
    if missing:
        raise SystemExit(
            f"{source}: no glyph for " +
            ", ".join(f"U+{c:04X}" for c in missing[:8]) +
            ("..." if len(missing) > 8 else "")
        )

    lines = [
        "/*",
        f" * Generated by tools/bdf2c.py from {source}. Do not edit.",
        " *",
    ]
    lines += [f" * {l}" for l in provenance(source)]
    lines += [
        " *",
        f" * Glyphs U+{FIRST:04X} to U+{LAST:04X}, then one for anything else.",
        f" * {HEIGHT} bytes each, one byte per row, MSB is the leftmost pixel.",
        " */",
        "",
        f"const unsigned char {symbol}[] = {{",
    ]

    for c in list(range(FIRST, LAST + 1)) + [None]:
        rows = UNKNOWN if c is None else glyphs[c]

        if len(rows) != HEIGHT:
            raise SystemExit(
                f"{source}: U+{c:04X} has {len(rows)} rows, expected {HEIGHT}."
            )

        name = "the unknown glyph" if c is None else (
            f"U+{c:04X} {chr(c)!r}" if c != 0x27 else "U+0027 apostrophe"
        )

        # Each byte next to the row it draws.
        #
        # It costs nothing in the image - comments do not survive the
        # compiler - and it makes a wrong conversion something a person can
        # see by reading this file, pairwise, instead of only by looking at a
        # screen and wondering. A shifted bit, a reversed row order or an
        # off-by-one in the range are all obvious here and all subtle there.
        lines.append(f"    /* {name} */")
        for r in rows:
            art = "".join("#" if r & (0x80 >> b) else "." for b in range(8))
            lines.append(f"    0x{r:02x},  /* {art} */")

    lines += [
        "};",
        "",
        f"const unsigned long {symbol}_len = sizeof({symbol});",
        "",
    ]

    with open(out, "w") as f:
        f.write("\n".join(lines))

    count = LAST - FIRST + 2
    print(f"{out}: {count} glyphs, {count * HEIGHT} bytes")


if __name__ == "__main__":
    main()
