#!/usr/bin/env python3
"""
The programs in user/bin/, as one Lua table.

There is no disk. A program has to reach the running system somehow, and
until M8 that is by being carried inside the image - the same way init.lua
is, and for the same reason.

What this emits is a C string holding *Lua source*: a chunk that returns a
table of name to source. The alternative was a C array of structs and a
loop in C to turn it into a Lua table, which is more code in the wrong
language to say the same thing.

The programs are read-only because they are in the image. `/bin` is a server
that serves this table and refuses writes, which is honest: you cannot edit
what is compiled in, and pretending otherwise would mean a write that
appears to work and vanishes at reboot.

Usage: progs2c.py <symbol> <out.c> <program.lua>...
"""

import os
import sys


def quote(source):
    """Lua long-bracket, with enough equals signs to be unambiguous.

    A program may itself contain `]]` or `]=]`, so the delimiter has to be
    longer than anything inside it. Counting rather than guessing: a program
    that happened to contain the delimiter would otherwise end its own string
    halfway through and fail to compile, with the error pointing at the
    wrong file.
    """
    level = 0
    while ("]" + "=" * level + "]") in source or ("[" + "=" * level + "[") in source:
        level += 1

    eq = "=" * level
    # A leading newline is skipped by Lua's long-bracket syntax, so one is
    # added: without it a program starting with a newline would silently lose
    # it and every line number in an error message would be off by one.
    return f"[{eq}[\n{source}]{eq}]"


def c_string(text):
    """A C string literal, split a line at a time so the file stays readable."""
    out = []

    for line in text.split("\n"):
        escaped = (line.replace("\\", "\\\\")
                       .replace('"', '\\"')
                       .replace("\t", "\\t"))
        out.append(f'    "{escaped}\\n"')

    return "\n".join(out)


def main():
    if len(sys.argv) < 4:
        raise SystemExit(__doc__.strip().splitlines()[-1])

    symbol, out_path, programs = sys.argv[1], sys.argv[2], sys.argv[3:]

    entries = []
    for path in sorted(programs):
        name = os.path.basename(path)
        with open(path) as f:
            entries.append(f"  [{name!r}] = {quote(f.read())},")

    lua = "return {\n" + "\n".join(entries) + "\n}\n"

    body = [
        "/*",
        f" * Generated by tools/progs2c.py from {len(programs)} program(s). Do not edit.",
        " *",
        " * Lua source for a chunk that returns a table of name to source. The",
        " * /bin server runs it once and serves what it gets.",
        " */",
        "",
        f"const char {symbol}[] =",
        c_string(lua),
        "    ;",
        "",
    ]

    with open(out_path, "w") as f:
        f.write("\n".join(body))

    print(f"{out_path}: {len(programs)} program(s), {len(lua)} bytes of Lua")


if __name__ == "__main__":
    main()
