#!/usr/bin/env python3
#  Kosmos. Copyright (c) 2026 Diego Cibils. MIT; see LICENSE.
"""The protocol stamp: which protocols an image speaks, as one word.

    python3 tools/protostamp.py OUT.c user/include/*proto.h user/include/*ring.h

An installed application carries its own runtime (`docs/elf.md` step 5), so
it speaks the protocols of the build that linked it - and on 4 October the
M700's Doom, linked for 0.10.205, read `ui.lua` misaligned from a program
store whose chunks had changed size: "ui.lua:1: unexpected symbol", from
deep inside the kit, and nothing said why (`roadmap.md`, an installed
application built for older protocols says so).

So every image carries this: the first sixteen hex digits of a SHA-256 over
the protocol headers, sorted by name, each as its bytes. The launcher puts
its own in the request that starts a program, and the program's runtime
compares it with the one it was built with before running anything; a
mismatch is refused with a sentence that says to build it again.

**Any change to a header changes it**, a comment included. That is the rule
`CLAUDE.md` already gives - when a protocol changes, the installed
applications are built again - made something the machine notices.

The stamp is written behind a marker, `KOSMOS-PROTOSTAMP:`, so a test can
find it in an image and change it (`run_loader.py`'s stale image).
"""

import hashlib
import os
import sys


def main():
    out, headers = sys.argv[1], sorted(sys.argv[2:], key=os.path.basename)
    digest = hashlib.sha256()

    for path in headers:
        digest.update(os.path.basename(path).encode() + b"\0")

        with open(path, "rb") as f:
            digest.update(f.read())

    stamp = digest.hexdigest()[:16]
    text = ("/* Kosmos. Copyright (c) 2026 Diego Cibils. MIT; see LICENSE. */\n"
            "/* Generated by tools/protostamp.py from %d protocol headers. */\n"
            "const char kosmos_protostamp[] = \"KOSMOS-PROTOSTAMP:%s\";\n"
            % (len(headers), stamp))

    os.makedirs(os.path.dirname(out) or ".", exist_ok=True)

    # Written only when it changes, so make sees a new stamp and nothing else.
    if not os.path.exists(out) or open(out).read() != text:
        with open(out, "w") as f:
            f.write(text)


if __name__ == "__main__":
    main()
