/* Kosmos. Copyright (c) 2026 Diego Cibils. MIT; see LICENSE. */
/*
 * Whether the canary can see a byte change - asked of the real pair.
 *
 * **The two halves are written in different languages and neither can check
 * the other at run time.** `tools/bin2c.py` computes the sums on the host in
 * Python; `kernel/image_sum.h` recomputes them on the machine in C, and if
 * the two ever disagree the boot log says the userland image is corrupt on
 * every machine, including the ones where it is not. A canary that cries on
 * a healthy boot is worse than no canary, because the next real one is read
 * as the same false alarm.
 *
 * So this compiles against a blob **generated by that script during the
 * build**, from a fixture the Makefile writes: the same path the init image
 * takes, on ten thousand bytes instead of three megabytes. If the Python and
 * the C ever part company, this stops.
 *
 * And the negative control, which is the half that matters: one byte of a
 * copy is changed, and the walk has to notice, name the page it is on, and
 * name only that one. A checker that always says "fine" passes the first
 * three checks here and fails the rest.
 *
 * Why a host test rather than a boot test: the fault this exists for is on a
 * ThinkPad and has never been reproduced under QEMU. What can be tested
 * without the machine is that the instrument works - so that when it says
 * something on the machine, the reading can be believed.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "../kernel/image_sum.h"

/* Generated during the build by tools/bin2c.py; see the Makefile. */
extern const unsigned char fixture[];
extern const unsigned long fixture_len;
extern const unsigned long fixture_sum;
extern const unsigned long fixture_page_bytes;
extern const unsigned long fixture_pages;
extern const unsigned      fixture_page_sum[];

static int checks;
static int fails;

static void check(int ok, const char *what)
{
    if (ok) {
        checks++;
    } else {
        fails++;
        printf("  %s\n", what);
    }
}

int main(void)
{
    struct image_sum_walk walk;
    unsigned char *copy;
    unsigned long bad_at, bad_page;

    /*
     * 1. **The canonical FNV-1a answers**, so that "Python and C agree" is
     *    not two implementations agreeing on the same mistake. These are
     *    the published vectors for the 64-bit and 32-bit variants.
     */
    check(image_sum64((const unsigned char *)"", 0) == 0xcbf29ce484222325UL,
          "FNV-1a 64 of nothing is not the basis");
    check(image_sum64((const unsigned char *)"a", 1) == 0xaf63dc4c8601ec8cUL,
          "FNV-1a 64 of \"a\" is not the published vector");
    check(image_sum64((const unsigned char *)"foobar", 6)
          == 0x85944171f73967e8UL,
          "FNV-1a 64 of \"foobar\" is not the published vector");
    check(image_sum32((const unsigned char *)"a", 1) == 0xe40c292cu,
          "FNV-1a 32 of \"a\" is not the published vector");
    check(image_sum32((const unsigned char *)"foobar", 6) == 0xbf9cf968u,
          "FNV-1a 32 of \"foobar\" is not the published vector");

    /*
     * 2. The build's own blob, unchanged: what every healthy boot must say.
     *    This is the check that fails if the script and the header ever
     *    stop computing the same thing.
     */
    check(image_sum64(fixture, fixture_len) == fixture_sum,
          "the whole-blob sum does not match what tools/bin2c.py wrote - "
          "the Python and the C have parted company, and every boot log "
          "will now call a healthy image corrupt");

    walk = image_sum_walk(fixture, fixture_len, fixture_page_bytes,
                          fixture_pages, fixture_page_sum);
    check(walk.bad == 0, "a page of an unchanged blob was called bad");

    /*
     * 3. The fixture is deliberately not a whole number of pages, because
     *    neither is any real blob: the last page is short, and hashing it
     *    over the padding after it instead of over its own bytes is the
     *    mistake that would make every boot report exactly one bad page -
     *    the last one - for ever.
     */
    check(fixture_len % fixture_page_bytes != 0,
          "the fixture is a whole number of pages, so the short-last-page "
          "case is not being tested at all");
    check(fixture_pages
          == (fixture_len + fixture_page_bytes - 1) / fixture_page_bytes,
          "the page count does not cover the blob");

    /*
     * 4. **The negative control.** One byte of a copy changed, in the
     *    middle of the second page, and every one of these must move.
     */
    copy = malloc(fixture_len);

    if (copy == NULL) {
        printf("FAIL: out of memory for the copy.\n");
        return 1;
    }

    memcpy(copy, fixture, fixture_len);

    bad_page = 1;
    bad_at = bad_page * fixture_page_bytes + 17;
    copy[bad_at] = (unsigned char)(copy[bad_at] ^ 0x01);

    check(image_sum64(copy, fixture_len) != fixture_sum,
          "one changed byte did not change the whole-blob sum");

    walk = image_sum_walk(copy, fixture_len, fixture_page_bytes,
                          fixture_pages, fixture_page_sum);
    check(walk.bad == 1, "one changed byte was not one bad page");
    check(walk.first == bad_page,
          "the walk named the wrong page for the changed byte");

    /*
     * 5. And in the short last page, which is the one a wrong length would
     *    silently skip.
     */
    memcpy(copy, fixture, fixture_len);
    copy[fixture_len - 1] = (unsigned char)(copy[fixture_len - 1] ^ 0x80);

    walk = image_sum_walk(copy, fixture_len, fixture_page_bytes,
                          fixture_pages, fixture_page_sum);
    check(walk.bad == 1, "a change in the short last page was not seen");
    check(walk.first == fixture_pages - 1,
          "the walk named the wrong page for a change in the last one");

    /*
     * 6. A change to every byte, so "bad" is a count rather than a flag.
     */
    memset(copy, 0x5a, fixture_len);

    walk = image_sum_walk(copy, fixture_len, fixture_page_bytes,
                          fixture_pages, fixture_page_sum);
    check(walk.bad == fixture_pages,
          "a blob changed end to end did not report every page");
    check(walk.first == 0, "the first bad page of a wholly changed blob "
                           "is not the first page");

    free(copy);

    if (fails > 0) {
        printf("FAIL: %d of %d checks on the userland image's canary.\n",
               fails, fails + checks);
        return 1;
    }

    printf("PASS: %d checks on the userland image's canary, over %lu bytes "
           "in %lu pages generated by tools/bin2c.py (the fault it watches "
           "for is a ThinkPad's and has never been reproduced here).\n",
           checks, fixture_len, fixture_pages);
    return 0;
}
