#!/usr/bin/env python3
#  Kosmos. Copyright (c) 2026 Diego Cibils. MIT; see LICENSE.
"""Wycheproof's AEAD vectors as a C header, for `tools/test_crypto.c`.

    python3 tools/wycheproof2c.py tools/vectors/wycheproof/aes_ccm_test.json out.h

Every test in the file, valid and invalid alike, as one `struct aead_vector`
each, in the file's order: the key, the nonce, the associated data, the
message, the ciphertext and the tag as bytes with their lengths, the test's
number, and whether Wycheproof says it must be accepted. Nothing is chosen
or left out here - which of them a primitive can be asked is the test's
decision, made where it can be read.
"""

import json
import sys


def array(name, hexdigits):
    data = bytes.fromhex(hexdigits)

    if not data:
        return "static const uint8_t %s[1] = {0};\n" % name, 0

    body = ",".join("0x%02x" % b for b in data)
    return "static const uint8_t %s[%d] = {%s};\n" % (name, len(data), body), len(data)


def main():
    source, out = sys.argv[1], sys.argv[2]

    with open(source) as f:
        d = json.load(f)

    lines = ["/* Generated by tools/wycheproof2c.py from %s; do not edit. */\n" % source,
             "/* Project Wycheproof, Apache License 2.0 (tools/vectors/wycheproof/LICENSE). */\n",
             "#include <stddef.h>\n#include <stdint.h>\n\n",
             "struct aead_vector {\n    int id, valid;\n",
             "    const uint8_t *key, *nonce, *aad, *msg, *ct, *tag;\n",
             "    size_t key_bytes, nonce_bytes, aad_bytes, msg_bytes, ct_bytes, tag_bytes;\n};\n\n"]
    rows = []

    for group in d["testGroups"]:
        for t in group["tests"]:
            n = t["tcId"]
            sizes = []

            for field in ("key", "iv", "aad", "msg", "ct", "tag"):
                text, size = array("v%d_%s" % (n, field), t[field])
                lines.append(text)
                sizes.append(size)

            rows.append("    {%d, %d, v%d_key, v%d_iv, v%d_aad, v%d_msg, v%d_ct, v%d_tag, %s},\n"
                        % (n, t["result"] == "valid", n, n, n, n, n, n,
                           ", ".join(str(s) for s in sizes)))

    # aes_ccm_test.json -> aes_ccm_vectors
    name = source.rsplit("/", 1)[-1].replace("_test.json", "") + "_vectors"
    lines.append("\nstatic const struct aead_vector %s[] = {\n" % name)
    lines.extend(rows)
    lines.append("};\n")

    with open(out, "w") as f:
        f.writelines(lines)


if __name__ == "__main__":
    main()
